"""asset hierarchy domain model

Revision ID: 08276baaeac2
Revises: 0001
Create Date: 2026-08-17 15:18:56.260296
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "08276baaeac2"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenant",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "SUSPENDED", name="tenantstatus", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant")),
        sa.UniqueConstraint("slug", name=op.f("uq_tenant_slug")),
    )
    op.create_table(
        "customer_account",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("region", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column(
            "service_tier",
            sa.Enum(
                "CONNECTED_MONITORING",
                "INTELLIGENT_DIAGNOSTICS",
                "PREDICTIVE_RELIABILITY",
                "PREMIUM_SERVICE",
                name="servicetier",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "commercial_status",
            sa.Enum(
                "PROSPECT",
                "PILOT",
                "ACTIVE",
                "SUSPENDED",
                "ENDED",
                name="commercialstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("contract_start", sa.Date(), nullable=True),
        sa.Column("contract_end", sa.Date(), nullable=True),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_customer_account_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_account")),
        sa.UniqueConstraint("tenant_id", "code", name=op.f("uq_customer_account_tenant_idcode")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_customer_account_tenant_idid")),
    )
    op.create_index(
        op.f("ix_customer_account_tenant_id"), "customer_account", ["tenant_id"], unique=False
    )
    op.create_table(
        "site",
        sa.Column("customer_account_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                "DECOMMISSIONED",
                name="operationalstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "customer_account_id"],
            ["customer_account.tenant_id", "customer_account.id"],
            name=op.f("fk_site_tenant_idcustomer_account_id_customer_account"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_site_tenant_id_tenant"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site")),
        sa.UniqueConstraint("tenant_id", "code", name=op.f("uq_site_tenant_idcode")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_site_tenant_idid")),
    )
    op.create_index(
        op.f("ix_site_customer_account_id"), "site", ["customer_account_id"], unique=False
    )
    op.create_index(op.f("ix_site_tenant_id"), "site", ["tenant_id"], unique=False)
    op.create_table(
        "plant",
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("plant_type", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                "DECOMMISSIONED",
                name="operationalstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["site.tenant_id", "site.id"],
            name=op.f("fk_plant_tenant_idsite_id_site"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_plant_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plant")),
        sa.UniqueConstraint("tenant_id", "code", name=op.f("uq_plant_tenant_idcode")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_plant_tenant_idid")),
    )
    op.create_index(op.f("ix_plant_site_id"), "plant", ["site_id"], unique=False)
    op.create_index(op.f("ix_plant_tenant_id"), "plant", ["tenant_id"], unique=False)
    op.create_table(
        "gateway",
        sa.Column("site_id", sa.Uuid(), nullable=True),
        sa.Column("plant_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("gateway_code", sa.String(length=50), nullable=False),
        sa.Column("manufacturer_demo", sa.String(length=150), nullable=True),
        sa.Column("model_demo", sa.String(length=150), nullable=True),
        sa.Column("firmware_version", sa.String(length=50), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                "DECOMMISSIONED",
                name="operationalstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(CASE WHEN site_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN plant_id IS NOT NULL THEN 1 ELSE 0 END) = 1",  # noqa: E501
            name=op.f("ck_gateway_exactly_one_attachment"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "plant_id"],
            ["plant.tenant_id", "plant.id"],
            name=op.f("fk_gateway_tenant_idplant_id_plant"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["site.tenant_id", "site.id"],
            name=op.f("fk_gateway_tenant_idsite_id_site"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_gateway_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gateway")),
        sa.UniqueConstraint(
            "tenant_id", "gateway_code", name=op.f("uq_gateway_tenant_idgateway_code")
        ),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_gateway_tenant_idid")),
    )
    op.create_index(op.f("ix_gateway_plant_id"), "gateway", ["plant_id"], unique=False)
    op.create_index(op.f("ix_gateway_site_id"), "gateway", ["site_id"], unique=False)
    op.create_index(op.f("ix_gateway_tenant_id"), "gateway", ["tenant_id"], unique=False)
    op.create_table(
        "production_line",
        sa.Column("plant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                "DECOMMISSIONED",
                name="operationalstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "criticality",
            sa.Enum(
                "LOW",
                "MEDIUM",
                "HIGH",
                "CRITICAL",
                name="criticality",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "plant_id"],
            ["plant.tenant_id", "plant.id"],
            name=op.f("fk_production_line_tenant_idplant_id_plant"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_production_line_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_line")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_production_line_tenant_idid")),
        sa.UniqueConstraint(
            "tenant_id", "plant_id", "code", name=op.f("uq_production_line_tenant_idplant_idcode")
        ),
    )
    op.create_index(
        op.f("ix_production_line_plant_id"), "production_line", ["plant_id"], unique=False
    )
    op.create_index(
        op.f("ix_production_line_tenant_id"), "production_line", ["tenant_id"], unique=False
    )
    op.create_table(
        "machine",
        sa.Column("production_line_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("asset_code", sa.String(length=50), nullable=False),
        sa.Column(
            "machine_type",
            sa.Enum(
                "CONVEYOR",
                "MOTOR",
                "FAN",
                "PUMP",
                "COMPRESSOR",
                "CRUSHER",
                name="machinetype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("manufacturer", sa.String(length=150), nullable=True),
        sa.Column("model", sa.String(length=150), nullable=True),
        sa.Column("serial_number_demo", sa.String(length=100), nullable=True),
        sa.Column("installation_date", sa.Date(), nullable=True),
        sa.Column(
            "criticality",
            sa.Enum(
                "LOW",
                "MEDIUM",
                "HIGH",
                "CRITICAL",
                name="criticality",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "operating_profile",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "REGISTERED",
                "COMMISSIONING",
                "BASELINING",
                "MONITORED",
                "MAINTENANCE",
                "OFFLINE",
                "RETIRED",
                name="machinestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "production_line_id"],
            ["production_line.tenant_id", "production_line.id"],
            name=op.f("fk_machine_tenant_idproduction_line_id_production_line"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_machine_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_machine")),
        sa.UniqueConstraint("tenant_id", "asset_code", name=op.f("uq_machine_tenant_idasset_code")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_machine_tenant_idid")),
    )
    op.create_index(
        op.f("ix_machine_production_line_id"), "machine", ["production_line_id"], unique=False
    )
    op.create_index(op.f("ix_machine_tenant_id"), "machine", ["tenant_id"], unique=False)
    op.create_table(
        "bearing",
        sa.Column("machine_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("position", sa.String(length=100), nullable=False),
        sa.Column("bearing_type", sa.String(length=100), nullable=True),
        sa.Column("manufacturer", sa.String(length=150), nullable=True),
        sa.Column("model", sa.String(length=150), nullable=True),
        sa.Column(
            "criticality",
            sa.Enum(
                "LOW",
                "MEDIUM",
                "HIGH",
                "CRITICAL",
                name="criticality",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("installation_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                "DECOMMISSIONED",
                name="operationalstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "machine_id"],
            ["machine.tenant_id", "machine.id"],
            name=op.f("fk_bearing_tenant_idmachine_id_machine"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_bearing_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bearing")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_bearing_tenant_idid")),
        sa.UniqueConstraint(
            "tenant_id",
            "machine_id",
            "position",
            name=op.f("uq_bearing_tenant_idmachine_idposition"),
        ),
    )
    op.create_index(op.f("ix_bearing_machine_id"), "bearing", ["machine_id"], unique=False)
    op.create_index(op.f("ix_bearing_tenant_id"), "bearing", ["tenant_id"], unique=False)
    op.create_table(
        "lubrication_system",
        sa.Column("machine_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "system_type",
            sa.Enum(
                "PROGRESSIVE",
                "SINGLE_LINE",
                "DUAL_LINE",
                "MULTI_LINE",
                name="lubricationsystemtype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("reservoir_id", sa.Uuid(), nullable=True),
        sa.Column("pump_id", sa.Uuid(), nullable=True),
        sa.Column("controller_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                "DECOMMISSIONED",
                name="operationalstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "commissioning_state",
            sa.Enum(
                "PLANNED",
                "COMMISSIONING",
                "COMMISSIONED",
                "DECOMMISSIONED",
                name="commissioningstate",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("configuration_version", sa.String(length=50), nullable=False),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "controller_id"],
            ["controller.tenant_id", "controller.id"],
            name="fk_controller_via_controller_id",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "machine_id"],
            ["machine.tenant_id", "machine.id"],
            name=op.f("fk_lubrication_system_tenant_idmachine_id_machine"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "pump_id"],
            ["pump.tenant_id", "pump.id"],
            name="fk_pump_via_pump_id",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "reservoir_id"],
            ["reservoir.tenant_id", "reservoir.id"],
            name="fk_reservoir_via_reservoir_id",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_lubrication_system_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lubrication_system")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_lubrication_system_tenant_idid")),
    )
    op.create_index(
        op.f("ix_lubrication_system_machine_id"), "lubrication_system", ["machine_id"], unique=False
    )
    op.create_index(
        op.f("ix_lubrication_system_tenant_id"), "lubrication_system", ["tenant_id"], unique=False
    )
    op.create_table(
        "controller",
        sa.Column("lubrication_system_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("controller_type", sa.String(length=100), nullable=True),
        sa.Column("manufacturer", sa.String(length=150), nullable=True),
        sa.Column("model", sa.String(length=150), nullable=True),
        sa.Column("firmware_version", sa.String(length=50), nullable=True),
        sa.Column("configuration_version", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                "DECOMMISSIONED",
                name="operationalstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "lubrication_system_id"],
            ["lubrication_system.tenant_id", "lubrication_system.id"],
            name=op.f("fk_controller_tenant_idlubrication_system_id_lubrication_system"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_controller_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_controller")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_controller_tenant_idid")),
    )
    op.create_index(
        op.f("ix_controller_lubrication_system_id"),
        "controller",
        ["lubrication_system_id"],
        unique=False,
    )
    op.create_index(op.f("ix_controller_tenant_id"), "controller", ["tenant_id"], unique=False)
    op.create_table(
        "distributor",
        sa.Column("lubrication_system_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=True),
        sa.Column("position", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                "DECOMMISSIONED",
                name="operationalstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "lubrication_system_id"],
            ["lubrication_system.tenant_id", "lubrication_system.id"],
            name=op.f("fk_distributor_tenant_idlubrication_system_id_lubrication_system"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_distributor_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_distributor")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_distributor_tenant_idid")),
    )
    op.create_index(
        op.f("ix_distributor_lubrication_system_id"),
        "distributor",
        ["lubrication_system_id"],
        unique=False,
    )
    op.create_index(op.f("ix_distributor_tenant_id"), "distributor", ["tenant_id"], unique=False)
    op.create_table(
        "pump",
        sa.Column("lubrication_system_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("pump_type", sa.String(length=100), nullable=True),
        sa.Column("manufacturer", sa.String(length=150), nullable=True),
        sa.Column("model", sa.String(length=150), nullable=True),
        sa.Column("controller_reference", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                "DECOMMISSIONED",
                name="operationalstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("firmware_version_demo", sa.String(length=50), nullable=True),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "lubrication_system_id"],
            ["lubrication_system.tenant_id", "lubrication_system.id"],
            name=op.f("fk_pump_tenant_idlubrication_system_id_lubrication_system"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_pump_tenant_id_tenant"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pump")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_pump_tenant_idid")),
    )
    op.create_index(
        op.f("ix_pump_lubrication_system_id"), "pump", ["lubrication_system_id"], unique=False
    )
    op.create_index(op.f("ix_pump_tenant_id"), "pump", ["tenant_id"], unique=False)
    op.create_table(
        "reservoir",
        sa.Column("lubrication_system_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("capacity_demo", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("capacity_unit", sa.String(length=20), nullable=True),
        sa.Column("lubricant_type_demo", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                "DECOMMISSIONED",
                name="operationalstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "lubrication_system_id"],
            ["lubrication_system.tenant_id", "lubrication_system.id"],
            name=op.f("fk_reservoir_tenant_idlubrication_system_id_lubrication_system"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_reservoir_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservoir")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_reservoir_tenant_idid")),
    )
    op.create_index(
        op.f("ix_reservoir_lubrication_system_id"),
        "reservoir",
        ["lubrication_system_id"],
        unique=False,
    )
    op.create_index(op.f("ix_reservoir_tenant_id"), "reservoir", ["tenant_id"], unique=False)
    op.create_table(
        "circuit",
        sa.Column("lubrication_system_id", sa.Uuid(), nullable=False),
        sa.Column("distributor_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                "DECOMMISSIONED",
                name="operationalstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "distributor_id"],
            ["distributor.tenant_id", "distributor.id"],
            name=op.f("fk_circuit_tenant_iddistributor_id_distributor"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "lubrication_system_id"],
            ["lubrication_system.tenant_id", "lubrication_system.id"],
            name=op.f("fk_circuit_tenant_idlubrication_system_id_lubrication_system"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_circuit_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_circuit")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_circuit_tenant_idid")),
        sa.UniqueConstraint(
            "tenant_id",
            "lubrication_system_id",
            "code",
            name=op.f("uq_circuit_tenant_idlubrication_system_idcode"),
        ),
    )
    op.create_index(op.f("ix_circuit_distributor_id"), "circuit", ["distributor_id"], unique=False)
    op.create_index(
        op.f("ix_circuit_lubrication_system_id"), "circuit", ["lubrication_system_id"], unique=False
    )
    op.create_index(op.f("ix_circuit_tenant_id"), "circuit", ["tenant_id"], unique=False)
    op.create_table(
        "lubrication_point",
        sa.Column("circuit_id", sa.Uuid(), nullable=False),
        sa.Column("bearing_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                "DECOMMISSIONED",
                name="operationalstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bearing_id"],
            ["bearing.tenant_id", "bearing.id"],
            name=op.f("fk_lubrication_point_tenant_idbearing_id_bearing"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "circuit_id"],
            ["circuit.tenant_id", "circuit.id"],
            name=op.f("fk_lubrication_point_tenant_idcircuit_id_circuit"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_lubrication_point_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lubrication_point")),
        sa.UniqueConstraint(
            "tenant_id",
            "circuit_id",
            "code",
            name=op.f("uq_lubrication_point_tenant_idcircuit_idcode"),
        ),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_lubrication_point_tenant_idid")),
    )
    op.create_index(
        op.f("ix_lubrication_point_bearing_id"), "lubrication_point", ["bearing_id"], unique=False
    )
    op.create_index(
        op.f("ix_lubrication_point_circuit_id"), "lubrication_point", ["circuit_id"], unique=False
    )
    op.create_index(
        op.f("ix_lubrication_point_tenant_id"), "lubrication_point", ["tenant_id"], unique=False
    )
    op.create_table(
        "sensor",
        sa.Column("sensor_code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "sensor_type",
            sa.Enum(
                "PRESSURE",
                "FLOW",
                "RESERVOIR_LEVEL",
                "PUMP_CURRENT",
                "PUMP_RUNTIME",
                "CYCLE_COMPLETION",
                "PISTON_MOVEMENT",
                "LUBRICANT_TEMPERATURE",
                "VIBRATION_RMS",
                "VIBRATION_PEAK",
                "BEARING_TEMPERATURE",
                "RPM",
                "LOAD",
                name="sensortype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("installation_date", sa.Date(), nullable=True),
        sa.Column("calibration_date", sa.Date(), nullable=True),
        sa.Column("firmware_version", sa.String(length=50), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                "FAULTY",
                "DECOMMISSIONED",
                name="sensorstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "quality_state",
            sa.Enum(
                "UNKNOWN",
                "GOOD",
                "DEGRADED",
                name="sensorqualitystate",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("machine_id", sa.Uuid(), nullable=True),
        sa.Column("bearing_id", sa.Uuid(), nullable=True),
        sa.Column("lubrication_system_id", sa.Uuid(), nullable=True),
        sa.Column("reservoir_id", sa.Uuid(), nullable=True),
        sa.Column("pump_id", sa.Uuid(), nullable=True),
        sa.Column("circuit_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(CASE WHEN machine_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN bearing_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN lubrication_system_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN reservoir_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN pump_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN circuit_id IS NOT NULL THEN 1 ELSE 0 END) = 1",  # noqa: E501
            name=op.f("ck_sensor_exactly_one_attachment"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bearing_id"],
            ["bearing.tenant_id", "bearing.id"],
            name=op.f("fk_sensor_tenant_idbearing_id_bearing"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "circuit_id"],
            ["circuit.tenant_id", "circuit.id"],
            name=op.f("fk_sensor_tenant_idcircuit_id_circuit"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "lubrication_system_id"],
            ["lubrication_system.tenant_id", "lubrication_system.id"],
            name=op.f("fk_sensor_tenant_idlubrication_system_id_lubrication_system"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "machine_id"],
            ["machine.tenant_id", "machine.id"],
            name=op.f("fk_sensor_tenant_idmachine_id_machine"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "pump_id"],
            ["pump.tenant_id", "pump.id"],
            name=op.f("fk_sensor_tenant_idpump_id_pump"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "reservoir_id"],
            ["reservoir.tenant_id", "reservoir.id"],
            name=op.f("fk_sensor_tenant_idreservoir_id_reservoir"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_sensor_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sensor")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_sensor_tenant_idid")),
        sa.UniqueConstraint(
            "tenant_id", "sensor_code", name=op.f("uq_sensor_tenant_idsensor_code")
        ),
    )
    op.create_index(op.f("ix_sensor_bearing_id"), "sensor", ["bearing_id"], unique=False)
    op.create_index(op.f("ix_sensor_circuit_id"), "sensor", ["circuit_id"], unique=False)
    op.create_index(
        op.f("ix_sensor_lubrication_system_id"), "sensor", ["lubrication_system_id"], unique=False
    )
    op.create_index(op.f("ix_sensor_machine_id"), "sensor", ["machine_id"], unique=False)
    op.create_index(op.f("ix_sensor_pump_id"), "sensor", ["pump_id"], unique=False)
    op.create_index(op.f("ix_sensor_reservoir_id"), "sensor", ["reservoir_id"], unique=False)
    op.create_index(op.f("ix_sensor_tenant_id"), "sensor", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sensor_tenant_id"), table_name="sensor")
    op.drop_index(op.f("ix_sensor_reservoir_id"), table_name="sensor")
    op.drop_index(op.f("ix_sensor_pump_id"), table_name="sensor")
    op.drop_index(op.f("ix_sensor_machine_id"), table_name="sensor")
    op.drop_index(op.f("ix_sensor_lubrication_system_id"), table_name="sensor")
    op.drop_index(op.f("ix_sensor_circuit_id"), table_name="sensor")
    op.drop_index(op.f("ix_sensor_bearing_id"), table_name="sensor")
    op.drop_table("sensor")
    op.drop_index(op.f("ix_lubrication_point_tenant_id"), table_name="lubrication_point")
    op.drop_index(op.f("ix_lubrication_point_circuit_id"), table_name="lubrication_point")
    op.drop_index(op.f("ix_lubrication_point_bearing_id"), table_name="lubrication_point")
    op.drop_table("lubrication_point")
    op.drop_index(op.f("ix_circuit_tenant_id"), table_name="circuit")
    op.drop_index(op.f("ix_circuit_lubrication_system_id"), table_name="circuit")
    op.drop_index(op.f("ix_circuit_distributor_id"), table_name="circuit")
    op.drop_table("circuit")
    op.drop_index(op.f("ix_reservoir_tenant_id"), table_name="reservoir")
    op.drop_index(op.f("ix_reservoir_lubrication_system_id"), table_name="reservoir")
    op.drop_table("reservoir")
    op.drop_index(op.f("ix_pump_tenant_id"), table_name="pump")
    op.drop_index(op.f("ix_pump_lubrication_system_id"), table_name="pump")
    op.drop_table("pump")
    op.drop_index(op.f("ix_distributor_tenant_id"), table_name="distributor")
    op.drop_index(op.f("ix_distributor_lubrication_system_id"), table_name="distributor")
    op.drop_table("distributor")
    op.drop_index(op.f("ix_controller_tenant_id"), table_name="controller")
    op.drop_index(op.f("ix_controller_lubrication_system_id"), table_name="controller")
    op.drop_table("controller")
    op.drop_index(op.f("ix_lubrication_system_tenant_id"), table_name="lubrication_system")
    op.drop_index(op.f("ix_lubrication_system_machine_id"), table_name="lubrication_system")
    op.drop_table("lubrication_system")
    op.drop_index(op.f("ix_bearing_tenant_id"), table_name="bearing")
    op.drop_index(op.f("ix_bearing_machine_id"), table_name="bearing")
    op.drop_table("bearing")
    op.drop_index(op.f("ix_machine_tenant_id"), table_name="machine")
    op.drop_index(op.f("ix_machine_production_line_id"), table_name="machine")
    op.drop_table("machine")
    op.drop_index(op.f("ix_production_line_tenant_id"), table_name="production_line")
    op.drop_index(op.f("ix_production_line_plant_id"), table_name="production_line")
    op.drop_table("production_line")
    op.drop_index(op.f("ix_gateway_tenant_id"), table_name="gateway")
    op.drop_index(op.f("ix_gateway_site_id"), table_name="gateway")
    op.drop_index(op.f("ix_gateway_plant_id"), table_name="gateway")
    op.drop_table("gateway")
    op.drop_index(op.f("ix_plant_tenant_id"), table_name="plant")
    op.drop_index(op.f("ix_plant_site_id"), table_name="plant")
    op.drop_table("plant")
    op.drop_index(op.f("ix_site_tenant_id"), table_name="site")
    op.drop_index(op.f("ix_site_customer_account_id"), table_name="site")
    op.drop_table("site")
    op.drop_index(op.f("ix_customer_account_tenant_id"), table_name="customer_account")
    op.drop_table("customer_account")
    op.drop_table("tenant")
    # ### end Alembic commands ###
