"""knowledge_document_tenant_scoped_unique

Revision ID: 0f3855b92037
Revises: 1769715b3831
Create Date: 2026-08-19 01:28:47.236603

Real bug fix (ADR-140): `uq_knowledge_document_key_version` was global
`(document_key, version)`, not tenant-scoped — two different tenants ingesting a document
under the same key/version collided, and the second tenant's "idempotent ingest" silently
returned the first tenant's row. Widened to `(tenant_id, document_key, version)`.

Also drops/recreates `ix_feature_vector_tenant_machine_set_time`/
`ix_telemetry_tenant_machine_time`/`ix_telemetry_tenant_sensor_time` with no actual DDL
difference — the same pre-existing DESC-index comparison false positive documented since
ADR-022 (also seen in `1f9fe8b7b163`, `db57458c6150`, `4762c2a0e92c`, `13d670ebdb0c`,
`b2aeeb8329ab`, `1769715b3831`). Removed from both `upgrade()`/`downgrade()` below.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0f3855b92037"
down_revision: str | None = "1769715b3831"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_knowledge_document_key_version"), "knowledge_document", type_="unique"
    )  # noqa: E501
    op.create_unique_constraint(
        "uq_knowledge_document_key_version",
        "knowledge_document",
        ["tenant_id", "document_key", "version"],
    )  # noqa: E501
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_knowledge_document_key_version", "knowledge_document", type_="unique")
    op.create_unique_constraint(
        op.f("uq_knowledge_document_key_version"),
        "knowledge_document",
        ["document_key", "version"],
        postgresql_nulls_not_distinct=False,
    )  # noqa: E501
    # ### end Alembic commands ###
