"""audit_event

Revision ID: 12a414daf64c
Revises: 0f3855b92037
Create Date: 2026-08-19 02:05:26.605057
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '12a414daf64c'
down_revision: str | None = '0f3855b92037'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('actor_id', sa.String(length=150), nullable=False),
    sa.Column('actor_type', sa.Enum('HUMAN', 'SYSTEM', 'AGENT', name='auditactortype', native_enum=False, length=32), nullable=False),  # noqa: E501
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('before_summary', sa.Text(), nullable=True),
    sa.Column('after_summary', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),  # noqa: E501
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),  # noqa: E501
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_audit_event_tenant_id_tenant'), ondelete='RESTRICT'),  # noqa: E501
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_event')),
    sa.UniqueConstraint('tenant_id', 'id', name=op.f('uq_audit_event_tenant_idid'))
    )
    op.create_index(op.f('ix_audit_event_action'), 'audit_event', ['action'], unique=False)
    op.create_index(op.f('ix_audit_event_actor_id'), 'audit_event', ['actor_id'], unique=False)
    op.create_index('ix_audit_event_correlation', 'audit_event', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_event_entity_id'), 'audit_event', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_event_entity_type'), 'audit_event', ['entity_type'], unique=False)  # noqa: E501
    op.create_index('ix_audit_event_tenant_actor_time', 'audit_event', ['tenant_id', 'actor_id', sa.literal_column('created_at DESC')], unique=False)  # noqa: E501
    op.create_index('ix_audit_event_tenant_entity', 'audit_event', ['tenant_id', 'entity_type', 'entity_id'], unique=False)  # noqa: E501
    op.create_index(op.f('ix_audit_event_tenant_id'), 'audit_event', ['tenant_id'], unique=False)
    op.create_index('ix_audit_event_tenant_time', 'audit_event', ['tenant_id', sa.literal_column('created_at DESC')], unique=False)  # noqa: E501
    # NOTE: autogenerate also proposed dropping ix_feature_vector_tenant_machine_set_time
    # and the two ix_telemetry_tenant_* DESC indexes here — the known DESC-index
    # autogenerate false positive (unrelated to this migration's actual change; see
    # ADR-022 and `alembic check`'s documented pre-existing diff). Not applied.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_event_tenant_time', table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_tenant_id'), table_name='audit_event')
    op.drop_index('ix_audit_event_tenant_entity', table_name='audit_event')
    op.drop_index('ix_audit_event_tenant_actor_time', table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_entity_type'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_entity_id'), table_name='audit_event')
    op.drop_index('ix_audit_event_correlation', table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_actor_id'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_action'), table_name='audit_event')
    op.drop_table('audit_event')
    # ### end Alembic commands ###
