"""condition prognostic decision assessments

Revision ID: 13d670ebdb0c
Revises: 4762c2a0e92c
Create Date: 2026-08-18 21:58:06.527976

Autogenerate also proposed dropping/re-adding `ix_feature_vector_tenant_machine_set_time`,
`ix_telemetry_tenant_machine_time`, and `ix_telemetry_tenant_sensor_time` — the same known
`DESC`-index false positive documented in migrations `1f9fe8b7b163`, `db57458c6150`, and
`4762c2a0e92c` (autogenerate's index-signature comparison doesn't recognize `sa.text(...)
DESC`-built indexes as unchanged). Those three indexes are intentionally left untouched by
this migration.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "13d670ebdb0c"
down_revision: str | None = "4762c2a0e92c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "condition_assessment",
        sa.Column("machine_id", sa.Uuid(), nullable=False),
        sa.Column("component_id", sa.Uuid(), nullable=True),
        sa.Column(
            "condition_type",
            sa.Enum(
                "NORMAL_OPERATION",
                "LUBRICATION_DELIVERY_DEGRADATION",
                "DEVELOPING_RESTRICTION_PATTERN",
                "DELIVERY_BLOCKAGE_PATTERN",
                "POSSIBLE_LEAKAGE_PATTERN",
                "PUMP_PERFORMANCE_DEGRADATION",
                "LOW_LUBRICANT_AVAILABILITY",
                "BEARING_CONDITION_DEGRADATION",
                "INDEPENDENT_BEARING_CONDITION",
                "SENSOR_OR_DATA_QUALITY_LIMITATION",
                "INSUFFICIENT_EVIDENCE",
                "AMBIGUOUS_CONDITION",
                name="conditiontype",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "lifecycle_state",
            sa.Enum(
                "DETECTED",
                "DEVELOPING",
                "PERSISTENT",
                "IMPROVING",
                "RESOLVED",
                name="conditionlifecycle",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "severity",
            sa.Enum(
                "INFO",
                "WARNING",
                "HIGH",
                "CRITICAL",
                name="conditionseverity",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "confidence",
            sa.Enum(
                "LOW", "MODERATE", "HIGH", name="conditionconfidence", native_enum=False, length=32
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column("as_of_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "evidence_summary",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "rule_finding_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "ml_result_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "state_estimate_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "quality_context",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "baseline_versions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "instrumentation_coverage",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "limitations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),  # noqa: E501
        sa.Column("recommended_next_evidence", sa.Text(), nullable=True),
        sa.Column("policy_version", sa.String(length=20), nullable=False),
        sa.Column("engine_version", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tenant_id", "machine_id"],
            ["machine.tenant_id", "machine.id"],
            name=op.f("fk_condition_assessment_tenant_idmachine_id_machine"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_condition_assessment_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_condition_assessment")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_condition_assessment_tenant_idid")),
    )
    op.create_index(
        op.f("ix_condition_assessment_as_of_timestamp"),
        "condition_assessment",
        ["as_of_timestamp"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        op.f("ix_condition_assessment_component_id"),
        "condition_assessment",
        ["component_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        op.f("ix_condition_assessment_condition_type"),
        "condition_assessment",
        ["condition_type"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        op.f("ix_condition_assessment_machine_id"),
        "condition_assessment",
        ["machine_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        op.f("ix_condition_assessment_tenant_id"),
        "condition_assessment",
        ["tenant_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        "ix_condition_assessment_tenant_machine_time",
        "condition_assessment",
        ["tenant_id", "machine_id", sa.literal_column("as_of_timestamp DESC")],
        unique=False,
    )  # noqa: E501
    op.create_table(
        "decision_assessment",
        sa.Column("machine_id", sa.Uuid(), nullable=False),
        sa.Column("component_id", sa.Uuid(), nullable=True),
        sa.Column("condition_assessment_id", sa.Uuid(), nullable=False),
        sa.Column("prognostic_assessment_id", sa.Uuid(), nullable=True),
        sa.Column(
            "priority",
            sa.Enum(
                "MONITOR",
                "PLANNED",
                "HIGH",
                "URGENT",
                name="decisionpriority",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "recommended_action",
            sa.Enum(
                "CONTINUE_MONITORING",
                "VERIFY_SENSOR",
                "INSPECT_LUBRICATION_PATH",
                "INSPECT_DISTRIBUTOR",
                "CHECK_RESERVOIR",
                "CHECK_PUMP",
                "INSPECT_BEARING",
                "SCHEDULE_MAINTENANCE",
                "REQUEST_ADDITIONAL_MEASUREMENT",
                name="recommendedaction",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "recommended_window",
            sa.Enum(
                "NOW",
                "WITHIN_HOURS",
                "NEXT_PLANNED_MAINTENANCE",
                "MONITOR",
                name="recommendedwindow",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column("risk_if_deferred", sa.Text(), nullable=False),
        sa.Column("human_review_required", sa.Boolean(), nullable=False),
        sa.Column(
            "evidence", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),  # noqa: E501
        sa.Column(
            "confidence",
            sa.Enum(
                "LOW", "MODERATE", "HIGH", name="conditionconfidence", native_enum=False, length=32
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "limitations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "lifecycle_state",
            sa.Enum(
                "ACTIVE",
                "SUPERSEDED",
                "EXPIRED",
                "RESOLVED",
                name="decisionlifecycle",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column("as_of_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("policy_version", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tenant_id", "machine_id"],
            ["machine.tenant_id", "machine.id"],
            name=op.f("fk_decision_assessment_tenant_idmachine_id_machine"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_decision_assessment_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decision_assessment")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_decision_assessment_tenant_idid")),
    )
    op.create_index(
        op.f("ix_decision_assessment_as_of_timestamp"),
        "decision_assessment",
        ["as_of_timestamp"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        op.f("ix_decision_assessment_component_id"),
        "decision_assessment",
        ["component_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        op.f("ix_decision_assessment_condition_assessment_id"),
        "decision_assessment",
        ["condition_assessment_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        op.f("ix_decision_assessment_machine_id"),
        "decision_assessment",
        ["machine_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        op.f("ix_decision_assessment_prognostic_assessment_id"),
        "decision_assessment",
        ["prognostic_assessment_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        op.f("ix_decision_assessment_tenant_id"), "decision_assessment", ["tenant_id"], unique=False
    )  # noqa: E501
    op.create_index(
        "ix_decision_assessment_tenant_machine_time",
        "decision_assessment",
        ["tenant_id", "machine_id", sa.literal_column("as_of_timestamp DESC")],
        unique=False,
    )  # noqa: E501
    op.create_table(
        "prognostic_assessment",
        sa.Column("machine_id", sa.Uuid(), nullable=False),
        sa.Column("component_id", sa.Uuid(), nullable=True),
        sa.Column("state_estimate_id", sa.Uuid(), nullable=False),
        sa.Column(
            "state_type",
            sa.Enum(
                "LUBRICATION_DELIVERY_STATE",
                "BEARING_CONDITION_STATE",
                name="statetype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "horizon",
            sa.Enum(
                "ONE_HOUR",
                "SIX_HOURS",
                "TWENTY_FOUR_HOURS",
                name="forecasthorizon",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "status",
            sa.Enum(
                "OK", "NO_RELIABLE_FORECAST", name="prognosticstatus", native_enum=False, length=32
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column("as_of_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_state", sa.Float(), nullable=False),
        sa.Column(
            "trend",
            sa.Enum(
                "IMPROVING",
                "STABLE",
                "DETERIORATING",
                "UNKNOWN",
                name="statetrend",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column("predicted_state_at_horizon", sa.Float(), nullable=True),
        sa.Column("estimated_threshold_crossing_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "uncertainty",
            sa.Enum(
                "LOW",
                "MODERATE",
                "HIGH",
                name="stateuncertaintycategory",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column("data_sufficient", sa.Boolean(), nullable=False),
        sa.Column(
            "limitations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),  # noqa: E501
        sa.Column("engine_version", sa.String(length=20), nullable=False),
        sa.Column("config_version", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tenant_id", "machine_id"],
            ["machine.tenant_id", "machine.id"],
            name=op.f("fk_prognostic_assessment_tenant_idmachine_id_machine"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_prognostic_assessment_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prognostic_assessment")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_prognostic_assessment_tenant_idid")),
    )
    op.create_index(
        op.f("ix_prognostic_assessment_as_of_timestamp"),
        "prognostic_assessment",
        ["as_of_timestamp"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        op.f("ix_prognostic_assessment_component_id"),
        "prognostic_assessment",
        ["component_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        op.f("ix_prognostic_assessment_machine_id"),
        "prognostic_assessment",
        ["machine_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        op.f("ix_prognostic_assessment_state_estimate_id"),
        "prognostic_assessment",
        ["state_estimate_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        op.f("ix_prognostic_assessment_tenant_id"),
        "prognostic_assessment",
        ["tenant_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        "ix_prognostic_assessment_tenant_machine_state_time",
        "prognostic_assessment",
        [
            "tenant_id",
            "machine_id",
            "state_type",
            "horizon",
            sa.literal_column("as_of_timestamp DESC"),
        ],
        unique=False,
    )  # noqa: E501
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_prognostic_assessment_tenant_machine_state_time", table_name="prognostic_assessment"
    )  # noqa: E501
    op.drop_index(op.f("ix_prognostic_assessment_tenant_id"), table_name="prognostic_assessment")
    op.drop_index(
        op.f("ix_prognostic_assessment_state_estimate_id"), table_name="prognostic_assessment"
    )  # noqa: E501
    op.drop_index(op.f("ix_prognostic_assessment_machine_id"), table_name="prognostic_assessment")
    op.drop_index(op.f("ix_prognostic_assessment_component_id"), table_name="prognostic_assessment")
    op.drop_index(
        op.f("ix_prognostic_assessment_as_of_timestamp"), table_name="prognostic_assessment"
    )  # noqa: E501
    op.drop_table("prognostic_assessment")
    op.drop_index("ix_decision_assessment_tenant_machine_time", table_name="decision_assessment")
    op.drop_index(op.f("ix_decision_assessment_tenant_id"), table_name="decision_assessment")
    op.drop_index(
        op.f("ix_decision_assessment_prognostic_assessment_id"), table_name="decision_assessment"
    )  # noqa: E501
    op.drop_index(op.f("ix_decision_assessment_machine_id"), table_name="decision_assessment")
    op.drop_index(
        op.f("ix_decision_assessment_condition_assessment_id"), table_name="decision_assessment"
    )  # noqa: E501
    op.drop_index(op.f("ix_decision_assessment_component_id"), table_name="decision_assessment")
    op.drop_index(op.f("ix_decision_assessment_as_of_timestamp"), table_name="decision_assessment")
    op.drop_table("decision_assessment")
    op.drop_index("ix_condition_assessment_tenant_machine_time", table_name="condition_assessment")
    op.drop_index(op.f("ix_condition_assessment_tenant_id"), table_name="condition_assessment")
    op.drop_index(op.f("ix_condition_assessment_machine_id"), table_name="condition_assessment")
    op.drop_index(op.f("ix_condition_assessment_condition_type"), table_name="condition_assessment")
    op.drop_index(op.f("ix_condition_assessment_component_id"), table_name="condition_assessment")
    op.drop_index(
        op.f("ix_condition_assessment_as_of_timestamp"), table_name="condition_assessment"
    )  # noqa: E501
    op.drop_table("condition_assessment")
    # ### end Alembic commands ###
