"""knowledge_agent

Revision ID: 1769715b3831
Revises: b2aeeb8329ab
Create Date: 2026-08-19 00:55:56.225702

Autogenerate proposed dropping and recreating `ix_feature_vector_tenant_machine_set_time`/
`ix_telemetry_tenant_machine_time`/`ix_telemetry_tenant_sensor_time` with no actual DDL
difference — the same pre-existing DESC-index comparison false positive documented since
ADR-022 (also seen in `1f9fe8b7b163`, `db57458c6150`, `4762c2a0e92c`, `13d670ebdb0c`,
`b2aeeb8329ab`). Removed from both `upgrade()`/`downgrade()` below.

Also required a manual `import pgvector.sqlalchemy` — autogenerate referenced
`pgvector.sqlalchemy.vector.VECTOR` for the new `knowledge_chunk.embedding` column without
adding the import itself.
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "1769715b3831"
down_revision: str | None = "b2aeeb8329ab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_session",
        sa.Column("machine_id", sa.Uuid(), nullable=True),
        sa.Column("incident_id", sa.Uuid(), nullable=True),
        sa.Column("maintenance_case_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_agent_session_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_session")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_agent_session_tenant_idid")),
    )
    op.create_index(
        op.f("ix_agent_session_incident_id"), "agent_session", ["incident_id"], unique=False
    )  # noqa: E501
    op.create_index(
        op.f("ix_agent_session_machine_id"), "agent_session", ["machine_id"], unique=False
    )  # noqa: E501
    op.create_index(
        op.f("ix_agent_session_maintenance_case_id"),
        "agent_session",
        ["maintenance_case_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        op.f("ix_agent_session_tenant_id"), "agent_session", ["tenant_id"], unique=False
    )  # noqa: E501
    op.create_table(
        "knowledge_document",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("document_key", sa.String(length=150), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum(
                "OPERATING_GUIDE",
                "SERVICE_PROCEDURE",
                "TROUBLESHOOTING_GUIDE",
                "COMPONENT_REFERENCE",
                "FAULT_CODE_REFERENCE",
                "SAFETY_NOTE",
                "SERVICE_CASE",
                name="documenttype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "REVIEW",
                "APPROVED",
                "RETIRED",
                name="documentstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source_name", sa.String(length=150), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.String(length=150), nullable=True),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_knowledge_document_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_document")),
        sa.UniqueConstraint("document_key", "version", name="uq_knowledge_document_key_version"),
    )
    op.create_index(
        op.f("ix_knowledge_document_document_key"),
        "knowledge_document",
        ["document_key"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        op.f("ix_knowledge_document_document_type"),
        "knowledge_document",
        ["document_type"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        op.f("ix_knowledge_document_status"), "knowledge_document", ["status"], unique=False
    )  # noqa: E501
    op.create_index(
        op.f("ix_knowledge_document_tenant_id"), "knowledge_document", ["tenant_id"], unique=False
    )  # noqa: E501
    op.create_index(
        "uq_knowledge_document_active_approved",
        "knowledge_document",
        ["tenant_id", "document_key"],
        unique=True,
        postgresql_where=sa.text("status = 'APPROVED'"),
    )  # noqa: E501
    op.create_table(
        "agent_message",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("USER", "ASSISTANT", name="agentmessagerole", native_enum=False, length=32),
            nullable=False,
        ),  # noqa: E501
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "response_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),  # noqa: E501
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tenant_id", "session_id"],
            ["agent_session.tenant_id", "agent_session.id"],
            name=op.f("fk_agent_message_tenant_idsession_id_agent_session"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_agent_message_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_message")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_agent_message_tenant_idid")),
    )
    op.create_index(
        op.f("ix_agent_message_session_id"), "agent_message", ["session_id"], unique=False
    )  # noqa: E501
    op.create_index(
        op.f("ix_agent_message_tenant_id"), "agent_message", ["tenant_id"], unique=False
    )  # noqa: E501
    op.create_index(
        "ix_agent_message_tenant_session_time",
        "agent_message",
        ["tenant_id", "session_id", "created_at"],
        unique=False,
    )  # noqa: E501
    op.create_table(
        "agent_tool_call",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("tool_name", sa.String(length=100), nullable=False),
        sa.Column(
            "arguments",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "status",
            sa.Enum(
                "OK", "ERROR", "DENIED", name="agenttoolcallstatus", native_enum=False, length=32
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column("result_summary", sa.Text(), nullable=False),
        sa.Column("correlation_id", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tenant_id", "session_id"],
            ["agent_session.tenant_id", "agent_session.id"],
            name=op.f("fk_agent_tool_call_tenant_idsession_id_agent_session"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_agent_tool_call_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_tool_call")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_agent_tool_call_tenant_idid")),
    )
    op.create_index(
        op.f("ix_agent_tool_call_session_id"), "agent_tool_call", ["session_id"], unique=False
    )  # noqa: E501
    op.create_index(
        op.f("ix_agent_tool_call_tenant_id"), "agent_tool_call", ["tenant_id"], unique=False
    )  # noqa: E501
    op.create_index(
        "ix_agent_tool_call_tenant_session_time",
        "agent_tool_call",
        ["tenant_id", "session_id", "created_at"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        op.f("ix_agent_tool_call_tool_name"), "agent_tool_call", ["tool_name"], unique=False
    )  # noqa: E501
    op.create_table(
        "knowledge_chunk",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("section", sa.String(length=150), nullable=False),
        sa.Column("heading", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("character_count", sa.Integer(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=256), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["knowledge_document.id"],
            name=op.f("fk_knowledge_chunk_document_id_knowledge_document"),
            ondelete="CASCADE",
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_chunk")),
        sa.UniqueConstraint("document_id", "ordinal", name="uq_knowledge_chunk_document_ordinal"),
    )
    op.create_index(
        op.f("ix_knowledge_chunk_document_id"), "knowledge_chunk", ["document_id"], unique=False
    )  # noqa: E501
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_knowledge_chunk_document_id"), table_name="knowledge_chunk")
    op.drop_table("knowledge_chunk")
    op.drop_index(op.f("ix_agent_tool_call_tool_name"), table_name="agent_tool_call")
    op.drop_index("ix_agent_tool_call_tenant_session_time", table_name="agent_tool_call")
    op.drop_index(op.f("ix_agent_tool_call_tenant_id"), table_name="agent_tool_call")
    op.drop_index(op.f("ix_agent_tool_call_session_id"), table_name="agent_tool_call")
    op.drop_table("agent_tool_call")
    op.drop_index("ix_agent_message_tenant_session_time", table_name="agent_message")
    op.drop_index(op.f("ix_agent_message_tenant_id"), table_name="agent_message")
    op.drop_index(op.f("ix_agent_message_session_id"), table_name="agent_message")
    op.drop_table("agent_message")
    op.drop_index(
        "uq_knowledge_document_active_approved",
        table_name="knowledge_document",
        postgresql_where=sa.text("status = 'APPROVED'"),
    )  # noqa: E501
    op.drop_index(op.f("ix_knowledge_document_tenant_id"), table_name="knowledge_document")
    op.drop_index(op.f("ix_knowledge_document_status"), table_name="knowledge_document")
    op.drop_index(op.f("ix_knowledge_document_document_type"), table_name="knowledge_document")
    op.drop_index(op.f("ix_knowledge_document_document_key"), table_name="knowledge_document")
    op.drop_table("knowledge_document")
    op.drop_index(op.f("ix_agent_session_tenant_id"), table_name="agent_session")
    op.drop_index(op.f("ix_agent_session_maintenance_case_id"), table_name="agent_session")
    op.drop_index(op.f("ix_agent_session_machine_id"), table_name="agent_session")
    op.drop_index(op.f("ix_agent_session_incident_id"), table_name="agent_session")
    op.drop_table("agent_session")
    # ### end Alembic commands ###
