"""energy_outcome_verification

Revision ID: 1cfcb500dbf0
Revises: ed804824fd91
Create Date: 2026-08-24 19:00:00.975890

Autogenerate also proposed dropping/re-adding `ix_feature_vector_tenant_machine_set_time`,
`ix_telemetry_tenant_machine_time`, and `ix_telemetry_tenant_sensor_time` — the same known
`DESC`-index false positive documented in migration `1f9fe8b7b163`/`db57458c6150`/
`4762c2a0e92c`/`c67d71dabca3`/`ed804824fd91` (autogenerate's index-signature comparison
doesn't recognize `sa.text(...) DESC`-built indexes as unchanged). Those three indexes are
intentionally left untouched by this migration.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "1cfcb500dbf0"
down_revision: str | None = "ed804824fd91"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "energy_outcome_verification",
        sa.Column("machine_id", sa.Uuid(), nullable=False),
        sa.Column("maintenance_case_id", sa.Uuid(), nullable=False),
        sa.Column("incident_id", sa.Uuid(), nullable=True),
        sa.Column("intervention_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("pre_window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pre_window_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("post_window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("post_window_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pre_mean_actual_power_kw", sa.Float(), nullable=True),
        sa.Column("pre_mean_expected_power_kw", sa.Float(), nullable=True),
        sa.Column("pre_mean_residual_kw", sa.Float(), nullable=True),
        sa.Column("pre_mean_residual_pct", sa.Float(), nullable=True),
        sa.Column("post_mean_actual_power_kw", sa.Float(), nullable=True),
        sa.Column("post_mean_expected_power_kw", sa.Float(), nullable=True),
        sa.Column("post_mean_residual_kw", sa.Float(), nullable=True),
        sa.Column("post_mean_residual_pct", sa.Float(), nullable=True),
        sa.Column("residual_change_kw", sa.Float(), nullable=True),
        sa.Column("residual_change_pct", sa.Float(), nullable=True),
        sa.Column(
            "comparability_status",
            sa.Enum(
                "COMPARABLE",
                "PARTIALLY_COMPARABLE",
                "NOT_COMPARABLE",
                "INSUFFICIENT_DATA",
                name="comparabilitystatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "comparison_confidence",
            sa.Enum(
                "LOW",
                "MODERATE",
                "HIGH",
                name="comparisonconfidence",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "energy_outcome_status",
            sa.Enum(
                "QUALIFIED_RECOVERY",
                "PROBABLE_RECOVERY",
                "NO_MATERIAL_CHANGE",
                "DETERIORATED",
                "INCONCLUSIVE",
                "INSUFFICIENT_DATA",
                name="energyoutcomestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("estimated_avoided_energy_kwh", sa.Float(), nullable=True),
        sa.Column(
            "energy_estimate_status",
            sa.Enum(
                "ESTIMATED",
                "NOT_QUALIFIED",
                "NOT_COMPARABLE",
                "INSUFFICIENT_DATA",
                name="energyestimatestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("pre_attribution_id", sa.Uuid(), nullable=True),
        sa.Column(
            "pre_attribution_level",
            sa.Enum(
                "NO_EVIDENCE",
                "POSSIBLE",
                "MODERATE",
                "STRONG",
                name="attributionlevel",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "condition_outcome_status",
            sa.Enum(
                "DETECTED",
                "DEVELOPING",
                "PERSISTENT",
                "IMPROVING",
                "RESOLVED",
                name="conditionlifecycle",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("maintenance_relevant", sa.Boolean(), nullable=False),
        sa.Column(
            "lubrication_association_status",
            sa.Enum(
                "NOT_APPLICABLE",
                "OBSERVED_ENERGY_CHANGE",
                "QUALIFIED_ENERGY_RECOVERY",
                "LUBRICATION_ASSOCIATED_RECOVERY",
                name="lubricationassociationstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "supporting_evidence",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "contradicting_evidence",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "limiting_factors",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "alternative_explanations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "provenance",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("policy_version", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "incident_id"],
            ["incident.tenant_id", "incident.id"],
            name=op.f("fk_energy_outcome_verification_tenant_idincident_id_incident"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "machine_id"],
            ["machine.tenant_id", "machine.id"],
            name=op.f("fk_energy_outcome_verification_tenant_idmachine_id_machine"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "maintenance_case_id"],
            ["maintenance_case.tenant_id", "maintenance_case.id"],
            name=op.f(
                "fk_energy_outcome_verification_tenant_idmaintenance_case_id_maintenance_case"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "pre_attribution_id"],
            ["lubrication_energy_attribution.tenant_id", "lubrication_energy_attribution.id"],
            name=op.f(
                "fk_energy_outcome_verification_tenant_idpre_attribution_id_"
                "lubrication_energy_attribution"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_energy_outcome_verification_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_energy_outcome_verification")),
        sa.UniqueConstraint(
            "tenant_id", "id", name=op.f("uq_energy_outcome_verification_tenant_idid")
        ),
    )
    op.create_index(
        op.f("ix_energy_outcome_verification_incident_id"),
        "energy_outcome_verification",
        ["incident_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_energy_outcome_verification_intervention_timestamp"),
        "energy_outcome_verification",
        ["intervention_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_energy_outcome_verification_machine_id"),
        "energy_outcome_verification",
        ["machine_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_energy_outcome_verification_maintenance_case_id"),
        "energy_outcome_verification",
        ["maintenance_case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_energy_outcome_verification_tenant_id"),
        "energy_outcome_verification",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_energy_outcome_verification_tenant_machine_time",
        "energy_outcome_verification",
        ["tenant_id", "machine_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_energy_outcome_verification_tenant_machine_time",
        table_name="energy_outcome_verification",
    )
    op.drop_index(
        op.f("ix_energy_outcome_verification_tenant_id"),
        table_name="energy_outcome_verification",
    )
    op.drop_index(
        op.f("ix_energy_outcome_verification_maintenance_case_id"),
        table_name="energy_outcome_verification",
    )
    op.drop_index(
        op.f("ix_energy_outcome_verification_machine_id"),
        table_name="energy_outcome_verification",
    )
    op.drop_index(
        op.f("ix_energy_outcome_verification_intervention_timestamp"),
        table_name="energy_outcome_verification",
    )
    op.drop_index(
        op.f("ix_energy_outcome_verification_incident_id"),
        table_name="energy_outcome_verification",
    )
    op.drop_table("energy_outcome_verification")
    # ### end Alembic commands ###
