"""telemetry pipeline

Revision ID: 1f9fe8b7b163
Revises: 08276baaeac2
Create Date: 2026-08-17 23:51:45.870064
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "1f9fe8b7b163"
down_revision: str | None = "08276baaeac2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telemetry_quarantine",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "SCHEMA_INVALID",
                "UNSUPPORTED_SCHEMA_VERSION",
                "UNKNOWN_TENANT",
                "UNKNOWN_SENSOR",
                "UNKNOWN_GATEWAY",
                "CROSS_TENANT_MISMATCH",
                "CONTEXT_CONFLICT",
                "PERSISTENT_FAILURE",
                name="quarantinereason",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("sensor_id", sa.Uuid(), nullable=True),
        sa.Column("gateway_id", sa.String(length=50), nullable=True),
        sa.Column("kafka_topic", sa.String(length=255), nullable=True),
        sa.Column("kafka_partition", sa.Integer(), nullable=True),
        sa.Column("kafka_offset", sa.BigInteger(), nullable=True),
        sa.Column("raw_payload", sa.Text(), nullable=False),
        sa.Column(
            "quarantined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telemetry_quarantine")),
    )
    op.create_index(
        op.f("ix_telemetry_quarantine_event_id"), "telemetry_quarantine", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_telemetry_quarantine_tenant_id"),
        "telemetry_quarantine",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "telemetry",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("schema_version", sa.String(length=10), nullable=False),
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=True),
        sa.Column("plant_id", sa.Uuid(), nullable=True),
        sa.Column("production_line_id", sa.Uuid(), nullable=True),
        sa.Column("machine_id", sa.Uuid(), nullable=True),
        sa.Column("bearing_id", sa.Uuid(), nullable=True),
        sa.Column("lubrication_system_id", sa.Uuid(), nullable=True),
        sa.Column("circuit_id", sa.Uuid(), nullable=True),
        sa.Column("lubrication_point_id", sa.Uuid(), nullable=True),
        sa.Column("sensor_id", sa.Uuid(), nullable=False),
        sa.Column(
            "measurement_type",
            sa.Enum(
                "PRESSURE",
                "FLOW",
                "RESERVOIR_LEVEL",
                "PUMP_CURRENT",
                "PUMP_RUNTIME",
                "CYCLE_COMPLETION",
                "PISTON_MOVEMENT",
                "LUBRICANT_TEMPERATURE",
                "VIBRATION_RMS",
                "VIBRATION_PEAK",
                "BEARING_TEMPERATURE",
                "RPM",
                "LOAD",
                name="sensortype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column(
            "quality",
            sa.Enum(
                "GOOD",
                "UNCERTAIN",
                "SUSPECT",
                "MISSING",
                "INVALID",
                "COMMUNICATION_LOSS",
                "BAD",
                "UNAVAILABLE",
                name="telemetryquality",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("operating_state", sa.String(length=50), nullable=False),
        sa.Column("source_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("edge_received_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("edge_emitted_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mqtt_received_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("kafka_published_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consumer_received_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "persisted_timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sequence_number", sa.BigInteger(), nullable=False),
        sa.Column("gateway_id", sa.String(length=50), nullable=False),
        sa.Column("device_id", sa.String(length=100), nullable=False),
        sa.Column("firmware_version", sa.String(length=50), nullable=True),
        sa.Column("controller_version", sa.String(length=50), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("kafka_partition", sa.Integer(), nullable=True),
        sa.Column("kafka_offset", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bearing_id"],
            ["bearing.tenant_id", "bearing.id"],
            name=op.f("fk_telemetry_tenant_idbearing_id_bearing"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "circuit_id"],
            ["circuit.tenant_id", "circuit.id"],
            name=op.f("fk_telemetry_tenant_idcircuit_id_circuit"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "lubrication_point_id"],
            ["lubrication_point.tenant_id", "lubrication_point.id"],
            name=op.f("fk_telemetry_tenant_idlubrication_point_id_lubrication_point"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "lubrication_system_id"],
            ["lubrication_system.tenant_id", "lubrication_system.id"],
            name=op.f("fk_telemetry_tenant_idlubrication_system_id_lubrication_system"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "machine_id"],
            ["machine.tenant_id", "machine.id"],
            name=op.f("fk_telemetry_tenant_idmachine_id_machine"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "plant_id"],
            ["plant.tenant_id", "plant.id"],
            name=op.f("fk_telemetry_tenant_idplant_id_plant"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "production_line_id"],
            ["production_line.tenant_id", "production_line.id"],
            name=op.f("fk_telemetry_tenant_idproduction_line_id_production_line"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "sensor_id"],
            ["sensor.tenant_id", "sensor.id"],
            name=op.f("fk_telemetry_tenant_idsensor_id_sensor"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["site.tenant_id", "site.id"],
            name=op.f("fk_telemetry_tenant_idsite_id_site"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_telemetry_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("event_id", "source_timestamp", name="pk_telemetry"),
    )
    op.create_index(op.f("ix_telemetry_gateway_id"), "telemetry", ["gateway_id"], unique=False)
    op.create_index(op.f("ix_telemetry_machine_id"), "telemetry", ["machine_id"], unique=False)
    op.create_index(op.f("ix_telemetry_sensor_id"), "telemetry", ["sensor_id"], unique=False)
    op.create_index(op.f("ix_telemetry_tenant_id"), "telemetry", ["tenant_id"], unique=False)
    # ### end Alembic commands ###
    # NOTE (correction, Phase 7): the three `fk_*_via_*_id` use_alter foreign keys on
    # `lubrication_system` (pump/reservoir/controller) detected here by autogenerate were
    # NOT a false positive — they were genuinely missing (08276baaeac2 declared them
    # `use_alter=True` inline in `op.create_table(...)`, which Alembic never turns into a
    # follow-up `ALTER TABLE`). This migration incorrectly suppressed the diff, leaving the
    # constraints absent from the database until they were actually created in migration
    # 5257a5e8e595 (Phase 7). Left un-repeated here (not this migration's job to re-fix);
    # see TECHNICAL_DECISIONS.md.

    # --- Phase 6: TimescaleDB hypertable + time-range query indexes (ADR-054) ---
    # source_timestamp (event time) is the partitioning column — see ADR-054 for why.
    # 1-day chunks: a deliberate demo/reference-scale choice, not a universal recommendation.
    op.execute(
        "SELECT create_hypertable("
        "'telemetry', 'source_timestamp', "
        "chunk_time_interval => INTERVAL '1 day', "
        "create_default_indexes => FALSE"
        ")"
    )
    op.create_index(
        "ix_telemetry_tenant_sensor_time",
        "telemetry",
        ["tenant_id", "sensor_id", sa.text("source_timestamp DESC")],
    )
    op.create_index(
        "ix_telemetry_tenant_machine_time",
        "telemetry",
        ["tenant_id", "machine_id", sa.text("source_timestamp DESC")],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_telemetry_tenant_machine_time", table_name="telemetry")
    op.drop_index("ix_telemetry_tenant_sensor_time", table_name="telemetry")
    op.drop_index(op.f("ix_telemetry_tenant_id"), table_name="telemetry")
    op.drop_index(op.f("ix_telemetry_sensor_id"), table_name="telemetry")
    op.drop_index(op.f("ix_telemetry_machine_id"), table_name="telemetry")
    op.drop_index(op.f("ix_telemetry_gateway_id"), table_name="telemetry")
    op.drop_table("telemetry")
    op.drop_index(op.f("ix_telemetry_quarantine_tenant_id"), table_name="telemetry_quarantine")
    op.drop_index(op.f("ix_telemetry_quarantine_event_id"), table_name="telemetry_quarantine")
    op.drop_table("telemetry_quarantine")
    # ### end Alembic commands ###
