"""baseline engine

Revision ID: 3366bbb38e2a
Revises: 5257a5e8e595
Create Date: 2026-08-18 10:01:58.180910
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "3366bbb38e2a"
down_revision: str | None = "5257a5e8e595"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "baseline_profile",
        sa.Column("sensor_id", sa.Uuid(), nullable=False),
        sa.Column("machine_id", sa.Uuid(), nullable=True),
        sa.Column(
            "measurement_type",
            sa.Enum(
                "PRESSURE",
                "FLOW",
                "RESERVOIR_LEVEL",
                "PUMP_CURRENT",
                "PUMP_RUNTIME",
                "CYCLE_COMPLETION",
                "PISTON_MOVEMENT",
                "LUBRICANT_TEMPERATURE",
                "VIBRATION_RMS",
                "VIBRATION_PEAK",
                "BEARING_TEMPERATURE",
                "RPM",
                "LOAD",
                name="sensortype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "strategy",
            sa.Enum(
                "STATIC_ENGINEERING_REFERENCE",
                "ROLLING_ASSET_BASELINE",
                "CONTEXTUAL_ASSET_BASELINE",
                name="baselinestrategytype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "metric_kind",
            sa.Enum(
                "STANDARD",
                "RESERVOIR_TREND",
                "CYCLE_METRIC",
                name="baselinemetrickind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("context_key", sa.String(length=200), nullable=False),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "INSUFFICIENT_DATA",
                "BUILDING",
                "ACTIVE",
                "STALE",
                "INVALIDATED",
                "SUPERSEDED",
                name="baselinestate",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("statistics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("min_sample_required", sa.Integer(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("window_seconds", sa.Float(), nullable=False),
        sa.Column("candidate_statistics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("candidate_sample_count", sa.Integer(), nullable=True),
        sa.Column("candidate_window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("candidate_window_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("candidate_first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("candidate_stable_cycles", sa.Integer(), nullable=False),
        sa.Column("config_version", sa.String(length=20), nullable=False),
        sa.Column("quality_policy_version", sa.String(length=20), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invalidation_reason", sa.String(length=255), nullable=True),
        sa.Column("last_evaluated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_interval_seconds", sa.Float(), nullable=False),
        sa.Column("stale_after_seconds", sa.Float(), nullable=False),
        sa.Column("firmware_version", sa.String(length=50), nullable=True),
        sa.Column("controller_version", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "machine_id"],
            ["machine.tenant_id", "machine.id"],
            name=op.f("fk_baseline_profile_tenant_idmachine_id_machine"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "sensor_id"],
            ["sensor.tenant_id", "sensor.id"],
            name=op.f("fk_baseline_profile_tenant_idsensor_id_sensor"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_baseline_profile_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_baseline_profile")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_baseline_profile_tenant_idid")),
        sa.UniqueConstraint(
            "tenant_id",
            "sensor_id",
            "strategy",
            "context_key",
            "version",
            name="uq_baseline_profile_version",
        ),
    )
    op.create_index(
        op.f("ix_baseline_profile_machine_id"), "baseline_profile", ["machine_id"], unique=False
    )
    op.create_index(
        op.f("ix_baseline_profile_sensor_id"), "baseline_profile", ["sensor_id"], unique=False
    )
    op.create_index(
        op.f("ix_baseline_profile_tenant_id"), "baseline_profile", ["tenant_id"], unique=False
    )
    op.create_index(
        "uq_baseline_profile_active",
        "baseline_profile",
        ["tenant_id", "sensor_id", "strategy", "context_key"],
        unique=True,
        postgresql_where=sa.text("state = 'ACTIVE'"),
    )
    # NOTE: autogenerate also proposed dropping `ix_telemetry_tenant_sensor_time`/
    # `ix_telemetry_tenant_machine_time` — the same documented false positive noted in
    # 5257a5e8e595 (those are real indexes created via raw `op.create_index(..., sa.text(...))`
    # for DESC ordering in 1f9fe8b7b163, which the declarative-model diff can't see). Not dropped.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: see matching NOTE in upgrade() — the DESC telemetry indexes are the documented
    # false positive and stay omitted here too.
    op.drop_index(
        "uq_baseline_profile_active",
        table_name="baseline_profile",
        postgresql_where=sa.text("state = 'ACTIVE'"),
    )
    op.drop_index(op.f("ix_baseline_profile_tenant_id"), table_name="baseline_profile")
    op.drop_index(op.f("ix_baseline_profile_sensor_id"), table_name="baseline_profile")
    op.drop_index(op.f("ix_baseline_profile_machine_id"), table_name="baseline_profile")
    op.drop_table("baseline_profile")
    # ### end Alembic commands ###
