"""state estimates

Revision ID: 4762c2a0e92c
Revises: db57458c6150
Create Date: 2026-08-18 20:36:37.736152

Autogenerate also proposed dropping/re-adding `ix_feature_vector_tenant_machine_set_time`,
`ix_telemetry_tenant_machine_time`, and `ix_telemetry_tenant_sensor_time` — the same known
`DESC`-index false positive documented in migration `1f9fe8b7b163` and `db57458c6150`
(autogenerate's index-signature comparison doesn't recognize `sa.text(...) DESC`-built
indexes as unchanged). Those three indexes are intentionally left untouched by this
migration.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "4762c2a0e92c"
down_revision: str | None = "db57458c6150"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "state_estimate",
        sa.Column("machine_id", sa.Uuid(), nullable=False),
        sa.Column("component_id", sa.Uuid(), nullable=True),
        sa.Column(
            "state_type",
            sa.Enum(
                "LUBRICATION_DELIVERY_STATE",
                "BEARING_CONDITION_STATE",
                name="statetype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column("as_of_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state_value", sa.Float(), nullable=False),
        sa.Column("state_rate", sa.Float(), nullable=False),
        sa.Column(
            "trend",
            sa.Enum(
                "IMPROVING",
                "STABLE",
                "DETERIORATING",
                "UNKNOWN",
                name="statetrend",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "uncertainty",
            sa.Enum(
                "LOW",
                "MODERATE",
                "HIGH",
                name="stateuncertaintycategory",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "covariance_summary",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),  # noqa: E501
        sa.Column("estimator_id", sa.String(length=100), nullable=False),
        sa.Column("estimator_version", sa.String(length=20), nullable=False),
        sa.Column("config_version", sa.String(length=20), nullable=False),
        sa.Column("feature_set", sa.String(length=80), nullable=False),
        sa.Column("feature_set_version", sa.String(length=20), nullable=False),
        sa.Column("feature_vector_id", sa.Uuid(), nullable=False),
        sa.Column("dt_seconds", sa.Float(), nullable=False),
        sa.Column("prediction_only", sa.Boolean(), nullable=False),
        sa.Column(
            "observations_used",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "observations_missing",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "quality_summary",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),  # noqa: E501
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tenant_id", "machine_id"],
            ["machine.tenant_id", "machine.id"],
            name=op.f("fk_state_estimate_tenant_idmachine_id_machine"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_state_estimate_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_state_estimate")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_state_estimate_tenant_idid")),
        sa.UniqueConstraint(
            "tenant_id",
            "machine_id",
            "state_type",
            "as_of_timestamp",
            "estimator_version",
            name="uq_state_estimate_logical",
        ),  # noqa: E501
    )
    op.create_index(
        op.f("ix_state_estimate_as_of_timestamp"),
        "state_estimate",
        ["as_of_timestamp"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        op.f("ix_state_estimate_component_id"), "state_estimate", ["component_id"], unique=False
    )  # noqa: E501
    op.create_index(
        op.f("ix_state_estimate_estimator_id"), "state_estimate", ["estimator_id"], unique=False
    )  # noqa: E501
    op.create_index(
        op.f("ix_state_estimate_feature_vector_id"),
        "state_estimate",
        ["feature_vector_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        op.f("ix_state_estimate_machine_id"), "state_estimate", ["machine_id"], unique=False
    )  # noqa: E501
    op.create_index(
        op.f("ix_state_estimate_tenant_id"), "state_estimate", ["tenant_id"], unique=False
    )  # noqa: E501
    op.create_index(
        "ix_state_estimate_tenant_machine_type_time",
        "state_estimate",
        ["tenant_id", "machine_id", "state_type", sa.literal_column("as_of_timestamp DESC")],
        unique=False,
    )  # noqa: E501
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_state_estimate_tenant_machine_type_time", table_name="state_estimate")
    op.drop_index(op.f("ix_state_estimate_tenant_id"), table_name="state_estimate")
    op.drop_index(op.f("ix_state_estimate_machine_id"), table_name="state_estimate")
    op.drop_index(op.f("ix_state_estimate_feature_vector_id"), table_name="state_estimate")
    op.drop_index(op.f("ix_state_estimate_estimator_id"), table_name="state_estimate")
    op.drop_index(op.f("ix_state_estimate_component_id"), table_name="state_estimate")
    op.drop_index(op.f("ix_state_estimate_as_of_timestamp"), table_name="state_estimate")
    op.drop_table("state_estimate")
    # ### end Alembic commands ###
