"""data quality engine

Revision ID: 5257a5e8e595
Revises: 1f9fe8b7b163
Create Date: 2026-08-18 02:00:40.353820
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "5257a5e8e595"
down_revision: str | None = "1f9fe8b7b163"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quality_assessment",
        sa.Column(
            "scope",
            sa.Enum("EVENT", "WINDOW", name="assessmentscope", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("sensor_id", sa.Uuid(), nullable=False),
        sa.Column("machine_id", sa.Uuid(), nullable=True),
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "quality_state",
            sa.Enum(
                "TRUSTED",
                "USABLE_WITH_CAUTION",
                "UNUSABLE",
                name="qualitystate",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column(
            "evaluated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("policy_version", sa.String(length=20), nullable=False),
        sa.Column(
            "rule_versions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "machine_id"],
            ["machine.tenant_id", "machine.id"],
            name=op.f("fk_quality_assessment_tenant_idmachine_id_machine"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "sensor_id"],
            ["sensor.tenant_id", "sensor.id"],
            name=op.f("fk_quality_assessment_tenant_idsensor_id_sensor"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_quality_assessment_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quality_assessment")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_quality_assessment_tenant_idid")),
    )
    op.create_index(
        op.f("ix_quality_assessment_evaluated_at"),
        "quality_assessment",
        ["evaluated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quality_assessment_event_id"), "quality_assessment", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_quality_assessment_machine_id"), "quality_assessment", ["machine_id"], unique=False
    )
    op.create_index(
        op.f("ix_quality_assessment_sensor_id"), "quality_assessment", ["sensor_id"], unique=False
    )
    op.create_index(
        op.f("ix_quality_assessment_tenant_id"), "quality_assessment", ["tenant_id"], unique=False
    )
    op.create_table(
        "sensor_quality_state",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("sensor_id", sa.Uuid(), nullable=False),
        sa.Column("machine_id", sa.Uuid(), nullable=True),
        sa.Column(
            "quality_state",
            sa.Enum(
                "TRUSTED",
                "USABLE_WITH_CAUTION",
                "UNUSABLE",
                name="qualitystate",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "eligibility",
            sa.Enum(
                "ELIGIBLE",
                "ELIGIBLE_WITH_CAUTION",
                "INELIGIBLE",
                name="eligibility",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("last_good_reading_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_good_reading_value", sa.Float(), nullable=True),
        sa.Column("last_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_observed_event_id", sa.Uuid(), nullable=True),
        sa.Column("last_observed_value", sa.Float(), nullable=True),
        sa.Column("last_observed_quality", sa.String(length=32), nullable=True),
        sa.Column("last_observed_operating_state", sa.String(length=50), nullable=True),
        sa.Column("last_source_timestamp_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expected_next_sequence", sa.BigInteger(), nullable=True),
        sa.Column(
            "staleness_status",
            sa.Enum(
                "FRESH", "STALE", "UNKNOWN", name="stalenessstatus", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "clock_status",
            sa.Enum(
                "NORMAL",
                "OFFSET_SUSPECTED",
                "DRIFT_SUSPECTED",
                "UNKNOWN",
                name="clockstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("active_issue_count", sa.Integer(), nullable=False),
        sa.Column("firmware_version", sa.String(length=50), nullable=True),
        sa.Column("controller_version", sa.String(length=50), nullable=True),
        sa.Column("policy_version", sa.String(length=20), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "machine_id"],
            ["machine.tenant_id", "machine.id"],
            name=op.f("fk_sensor_quality_state_tenant_idmachine_id_machine"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "sensor_id"],
            ["sensor.tenant_id", "sensor.id"],
            name=op.f("fk_sensor_quality_state_tenant_idsensor_id_sensor"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_sensor_quality_state_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "sensor_id", name="pk_sensor_quality_state"),
    )
    op.create_index(
        op.f("ix_sensor_quality_state_machine_id"),
        "sensor_quality_state",
        ["machine_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sensor_quality_state_tenant_id"),
        "sensor_quality_state",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "quality_issue",
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("sensor_id", sa.Uuid(), nullable=False),
        sa.Column("machine_id", sa.Uuid(), nullable=True),
        sa.Column(
            "dimension",
            sa.Enum(
                "COMPLETENESS",
                "VALIDITY",
                "TIMELINESS",
                "ORDERING",
                "CONSISTENCY",
                "COMMUNICATION",
                "SENSOR_HEALTH",
                "CONFIGURATION",
                "CONTEXT",
                name="qualitydimension",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "issue_type",
            sa.Enum(
                "MISSING_VALUE",
                "SEQUENCE_GAP",
                "OUT_OF_RANGE",
                "INVALID_VALUE",
                "UNIT_MISMATCH",
                "LATE_ARRIVAL",
                "VERY_LATE_ARRIVAL",
                "STALE_STREAM",
                "CLOCK_OFFSET_SUSPECTED",
                "CLOCK_DRIFT_SUSPECTED",
                "OUT_OF_ORDER",
                "DUPLICATE_PATTERN",
                "CONTEXT_INCONSISTENCY",
                "METADATA_INCONSISTENCY",
                "COMMUNICATION_LOSS",
                "SENSOR_DRIFT_SUSPECTED",
                "STUCK_SENSOR_SUSPECTED",
                "SPIKE_DETECTED",
                "CONFIG_CHANGE",
                name="qualityissuetype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "INFO",
                "WARNING",
                "ERROR",
                "CRITICAL",
                name="issueseverity",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE", "RECOVERING", "RESOLVED", name="issuestatus", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "evidence", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "affected_event_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "first_seen",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rule_id", sa.String(length=100), nullable=False),
        sa.Column("rule_version", sa.String(length=20), nullable=False),
        sa.Column("policy_version", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "assessment_id"],
            ["quality_assessment.tenant_id", "quality_assessment.id"],
            name=op.f("fk_quality_issue_tenant_idassessment_id_quality_assessment"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "machine_id"],
            ["machine.tenant_id", "machine.id"],
            name=op.f("fk_quality_issue_tenant_idmachine_id_machine"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "sensor_id"],
            ["sensor.tenant_id", "sensor.id"],
            name=op.f("fk_quality_issue_tenant_idsensor_id_sensor"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_quality_issue_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quality_issue")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_quality_issue_tenant_idid")),
        sa.UniqueConstraint(
            "tenant_id",
            "sensor_id",
            "rule_id",
            "rule_version",
            "event_id",
            name="uq_quality_issue_event_scope",
        ),
    )
    op.create_index(
        op.f("ix_quality_issue_assessment_id"), "quality_issue", ["assessment_id"], unique=False
    )
    op.create_index(
        op.f("ix_quality_issue_issue_type"), "quality_issue", ["issue_type"], unique=False
    )
    op.create_index(
        op.f("ix_quality_issue_machine_id"), "quality_issue", ["machine_id"], unique=False
    )
    op.create_index(
        op.f("ix_quality_issue_sensor_id"), "quality_issue", ["sensor_id"], unique=False
    )
    op.create_index(op.f("ix_quality_issue_severity"), "quality_issue", ["severity"], unique=False)
    op.create_index(op.f("ix_quality_issue_status"), "quality_issue", ["status"], unique=False)
    op.create_index(
        op.f("ix_quality_issue_tenant_id"), "quality_issue", ["tenant_id"], unique=False
    )
    op.create_index(
        "uq_quality_issue_active_window_scope",
        "quality_issue",
        ["tenant_id", "sensor_id", "rule_id", "rule_version"],
        unique=True,
        postgresql_where=sa.text("status IN ('ACTIVE', 'RECOVERING')"),
    )
    # NOTE (bugfix, discovered while regenerating this migration): the three
    # `fk_*_via_*_id` use_alter foreign keys on `lubrication_system` (pump/reservoir/
    # controller) were NEVER actually created in the database. They were declared with
    # `use_alter=True` inline inside `op.create_table(...)` in migration 08276baaeac2
    # (ADR "Composite Tenant FK / Cross-Tenant Reference Prevention"), intending Alembic to
    # emit them as a follow-up `ALTER TABLE`, matching how SQLAlchemy's
    # `MetaData.create_all()` handles `use_alter` cycles. But `op.create_table()` does not
    # do that follow-up emission itself — the DDL compiler simply omits `use_alter=True`
    # constraints from `CREATE TABLE` and nothing ever re-adds them. Migration 1f9fe8b7b163
    # (Phase 6) then misdiagnosed autogenerate's resulting "missing FK" diff as a false
    # positive and suppressed it, carrying the bug forward. Fixing it here with the
    # `ALTER TABLE` Alembic never emitted; see TECHNICAL_DECISIONS.md for the corrected ADR.
    op.create_foreign_key(
        "fk_pump_via_pump_id",
        "lubrication_system",
        "pump",
        ["tenant_id", "pump_id"],
        ["tenant_id", "id"],
        use_alter=True,
    )
    op.create_foreign_key(
        "fk_reservoir_via_reservoir_id",
        "lubrication_system",
        "reservoir",
        ["tenant_id", "reservoir_id"],
        ["tenant_id", "id"],
        use_alter=True,
    )
    op.create_foreign_key(
        "fk_controller_via_controller_id",
        "lubrication_system",
        "controller",
        ["tenant_id", "controller_id"],
        ["tenant_id", "id"],
        use_alter=True,
    )
    # NOTE: alembic autogenerate also proposed dropping
    # `ix_telemetry_tenant_sensor_time`/`ix_telemetry_tenant_machine_time` — this one IS a
    # genuine false positive: those are real indexes created via raw
    # `op.create_index(..., sa.text(...))` in 1f9fe8b7b163 (DESC ordering isn't
    # representable in the declarative model), so autogenerate's model-vs-reflection diff
    # can't see them and proposes dropping them. Not dropped.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: see matching NOTE in upgrade(). The raw-SQL DESC telemetry indexes are the one
    # genuine false positive and stay omitted here. The three use_alter FKs added in
    # upgrade() (bugfix) are dropped below to keep downgrade symmetric.
    op.drop_constraint("fk_controller_via_controller_id", "lubrication_system", type_="foreignkey")
    op.drop_constraint("fk_reservoir_via_reservoir_id", "lubrication_system", type_="foreignkey")
    op.drop_constraint("fk_pump_via_pump_id", "lubrication_system", type_="foreignkey")
    op.drop_index(
        "uq_quality_issue_active_window_scope",
        table_name="quality_issue",
        postgresql_where=sa.text("status IN ('ACTIVE', 'RECOVERING')"),
    )
    op.drop_index(op.f("ix_quality_issue_tenant_id"), table_name="quality_issue")
    op.drop_index(op.f("ix_quality_issue_status"), table_name="quality_issue")
    op.drop_index(op.f("ix_quality_issue_severity"), table_name="quality_issue")
    op.drop_index(op.f("ix_quality_issue_sensor_id"), table_name="quality_issue")
    op.drop_index(op.f("ix_quality_issue_machine_id"), table_name="quality_issue")
    op.drop_index(op.f("ix_quality_issue_issue_type"), table_name="quality_issue")
    op.drop_index(op.f("ix_quality_issue_assessment_id"), table_name="quality_issue")
    op.drop_table("quality_issue")
    op.drop_index(op.f("ix_sensor_quality_state_tenant_id"), table_name="sensor_quality_state")
    op.drop_index(op.f("ix_sensor_quality_state_machine_id"), table_name="sensor_quality_state")
    op.drop_table("sensor_quality_state")
    op.drop_index(op.f("ix_quality_assessment_tenant_id"), table_name="quality_assessment")
    op.drop_index(op.f("ix_quality_assessment_sensor_id"), table_name="quality_assessment")
    op.drop_index(op.f("ix_quality_assessment_machine_id"), table_name="quality_assessment")
    op.drop_index(op.f("ix_quality_assessment_event_id"), table_name="quality_assessment")
    op.drop_index(op.f("ix_quality_assessment_evaluated_at"), table_name="quality_assessment")
    op.drop_table("quality_assessment")
    # ### end Alembic commands ###
