"""rules engine

Revision ID: 615a5631e98e
Revises: 3366bbb38e2a
Create Date: 2026-08-18 11:02:24.113677
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "615a5631e98e"
down_revision: str | None = "3366bbb38e2a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rule_finding",
        sa.Column("machine_id", sa.Uuid(), nullable=False),
        sa.Column("component_id", sa.Uuid(), nullable=True),
        sa.Column("component_type", sa.String(length=30), nullable=False),
        sa.Column(
            "finding_type",
            sa.Enum(
                "FLOW_BELOW_CONTEXTUAL_BASELINE",
                "PRESSURE_ABOVE_CONTEXTUAL_BASELINE",
                "PRESSURE_BUILD_SLOW",
                "PUMP_CURRENT_ABOVE_BASELINE",
                "PUMP_RUNTIME_ABOVE_BASELINE",
                "CYCLE_DURATION_ABOVE_BASELINE",
                "CYCLE_COMPLETION_FAILURE",
                "RESERVOIR_LEVEL_LOW",
                "RESERVOIR_DEPLETION_ABNORMAL",
                "BEARING_TEMPERATURE_ABOVE_CONTEXTUAL_BASELINE",
                "VIBRATION_ABOVE_CONTEXTUAL_BASELINE",
                "FLOW_PRESSURE_RESTRICTION_PATTERN",
                "FLOW_PRESSURE_LEAKAGE_PATTERN",
                "PUMP_DEGRADATION_PATTERN",
                "LUBRICATION_PATH_DEGRADATION_PATTERN",
                "INDEPENDENT_BEARING_CONDITION_PATTERN",
                "INSUFFICIENT_TRUSTED_DATA",
                name="rulefindingtype",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("rule_id", sa.String(length=100), nullable=False),
        sa.Column("rule_version", sa.String(length=20), nullable=False),
        sa.Column("config_version", sa.String(length=20), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "HYDRAULIC",
                "PUMP",
                "RESERVOIR",
                "LUBRICATION_CYCLE",
                "BEARING_CONDITION",
                "SENSOR_QUALITY_DEPENDENT",
                "CROSS_SIGNAL",
                "CONFIGURATION",
                name="rulecategory",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "INFO",
                "WARNING",
                "HIGH",
                "CRITICAL",
                name="rulefindingseverity",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "CANDIDATE",
                "ACTIVE",
                "RECOVERING",
                "RESOLVED",
                name="rulefindingstate",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "evidence_strength",
            sa.Enum(
                "LOW", "MODERATE", "STRONG", name="evidencestrength", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("criticality_at_detection", sa.String(length=20), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "evidence", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "limitations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "quality_context",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "baseline_version_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "source_event_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("candidate_stable_cycles", sa.Integer(), nullable=False),
        sa.Column("first_detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "machine_id"],
            ["machine.tenant_id", "machine.id"],
            name=op.f("fk_rule_finding_tenant_idmachine_id_machine"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_rule_finding_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_finding")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_rule_finding_tenant_idid")),
    )
    op.create_index(
        op.f("ix_rule_finding_component_id"), "rule_finding", ["component_id"], unique=False
    )
    op.create_index(
        op.f("ix_rule_finding_finding_type"), "rule_finding", ["finding_type"], unique=False
    )
    op.create_index(
        op.f("ix_rule_finding_machine_id"), "rule_finding", ["machine_id"], unique=False
    )
    op.create_index(op.f("ix_rule_finding_severity"), "rule_finding", ["severity"], unique=False)
    op.create_index(op.f("ix_rule_finding_state"), "rule_finding", ["state"], unique=False)
    op.create_index(op.f("ix_rule_finding_tenant_id"), "rule_finding", ["tenant_id"], unique=False)
    op.create_index(
        "uq_rule_finding_active_scope",
        "rule_finding",
        ["tenant_id", "machine_id", "component_id", "rule_id", "rule_version"],
        unique=True,
        postgresql_where=sa.text("state IN ('CANDIDATE', 'ACTIVE', 'RECOVERING')"),
    )
    # NOTE: autogenerate also proposed dropping/recreating ix_telemetry_tenant_machine_time
    # and ix_telemetry_tenant_sensor_time — the known DESC-index false positive documented
    # in TECHNICAL_DECISIONS.md's ADR-022 correction (Phase 6/7 hit the same thing).
    # Deliberately not touched here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_rule_finding_active_scope",
        table_name="rule_finding",
        postgresql_where=sa.text("state IN ('CANDIDATE', 'ACTIVE', 'RECOVERING')"),
    )
    op.drop_index(op.f("ix_rule_finding_tenant_id"), table_name="rule_finding")
    op.drop_index(op.f("ix_rule_finding_state"), table_name="rule_finding")
    op.drop_index(op.f("ix_rule_finding_severity"), table_name="rule_finding")
    op.drop_index(op.f("ix_rule_finding_machine_id"), table_name="rule_finding")
    op.drop_index(op.f("ix_rule_finding_finding_type"), table_name="rule_finding")
    op.drop_index(op.f("ix_rule_finding_component_id"), table_name="rule_finding")
    op.drop_table("rule_finding")
    # ### end Alembic commands ###
