"""carbon_intelligence

Revision ID: 716000b357cd
Revises: 1cfcb500dbf0
Create Date: 2026-08-24 19:38:04.402334

Autogenerate also proposed dropping/re-adding `ix_feature_vector_tenant_machine_set_time`,
`ix_telemetry_tenant_machine_time`, and `ix_telemetry_tenant_sensor_time` — the same known
`DESC`-index false positive documented in migration `1f9fe8b7b163`/`db57458c6150`/
`4762c2a0e92c`/`c67d71dabca3`/`ed804824fd91`/`1cfcb500dbf0` (autogenerate's index-signature
comparison doesn't recognize `sa.text(...) DESC`-built indexes as unchanged). Those three
indexes are intentionally left untouched by this migration.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "716000b357cd"
down_revision: str | None = "1cfcb500dbf0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site_emission_factor",
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("factor_type", sa.String(length=30), nullable=False),
        sa.Column("factor_value", sa.Float(), nullable=False),
        sa.Column("factor_unit", sa.String(length=30), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "LOCATION_BASED", name="emissionfactormethod", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("source_name", sa.String(length=255), nullable=False),
        sa.Column("source_reference", sa.String(length=500), nullable=True),
        sa.Column("jurisdiction", sa.String(length=150), nullable=True),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "provenance",
            sa.Enum(
                "MEASURED_PLATFORM_METRIC",
                "DEMO_ESTIMATE",
                "CONFIGURED_TARGET",
                name="metricprovenance",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["site.tenant_id", "site.id"],
            name=op.f("fk_site_emission_factor_tenant_idsite_id_site"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_site_emission_factor_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_emission_factor")),
        sa.UniqueConstraint(
            "tenant_id", "id", name=op.f("uq_site_emission_factor_tenant_idid")
        ),
    )
    op.create_index(
        op.f("ix_site_emission_factor_site_id"),
        "site_emission_factor",
        ["site_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_site_emission_factor_tenant_id"),
        "site_emission_factor",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_site_emission_factor_tenant_site",
        "site_emission_factor",
        ["tenant_id", "site_id"],
        unique=False,
    )
    op.create_table(
        "carbon_impact_estimate",
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("machine_id", sa.Uuid(), nullable=False),
        sa.Column("energy_outcome_verification_id", sa.Uuid(), nullable=False),
        sa.Column("emission_factor_id", sa.Uuid(), nullable=True),
        sa.Column("observed_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("qualified_avoided_energy_kwh", sa.Float(), nullable=True),
        sa.Column("emission_factor_value", sa.Float(), nullable=True),
        sa.Column("emission_factor_unit", sa.String(length=30), nullable=True),
        sa.Column(
            "method",
            sa.Enum(
                "LOCATION_BASED", name="emissionfactormethod", native_enum=False, length=32
            ),
            nullable=True,
        ),
        sa.Column("estimated_co2e_kg", sa.Float(), nullable=True),
        sa.Column(
            "estimate_status",
            sa.Enum(
                "NOT_ELIGIBLE",
                "FACTOR_NOT_CONFIGURED",
                "FACTOR_NOT_APPLICABLE",
                "ESTIMATE_AVAILABLE",
                "LIMITED_ESTIMATE",
                name="carbonestimatestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "limitations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "provenance", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("policy_version", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "emission_factor_id"],
            ["site_emission_factor.tenant_id", "site_emission_factor.id"],
            name=op.f(
                "fk_carbon_impact_estimate_tenant_idemission_factor_id_site_emission_factor"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "energy_outcome_verification_id"],
            ["energy_outcome_verification.tenant_id", "energy_outcome_verification.id"],
            name=op.f(
                "fk_carbon_impact_estimate_tenant_idenergy_outcome_verification_id_"
                "energy_outcome_verification"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "machine_id"],
            ["machine.tenant_id", "machine.id"],
            name=op.f("fk_carbon_impact_estimate_tenant_idmachine_id_machine"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["site.tenant_id", "site.id"],
            name=op.f("fk_carbon_impact_estimate_tenant_idsite_id_site"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_carbon_impact_estimate_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_carbon_impact_estimate")),
        sa.UniqueConstraint(
            "tenant_id", "id", name=op.f("uq_carbon_impact_estimate_tenant_idid")
        ),
    )
    op.create_index(
        op.f("ix_carbon_impact_estimate_emission_factor_id"),
        "carbon_impact_estimate",
        ["emission_factor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_carbon_impact_estimate_energy_outcome_verification_id"),
        "carbon_impact_estimate",
        ["energy_outcome_verification_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_carbon_impact_estimate_machine_id"),
        "carbon_impact_estimate",
        ["machine_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_carbon_impact_estimate_site_id"),
        "carbon_impact_estimate",
        ["site_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_carbon_impact_estimate_tenant_id"),
        "carbon_impact_estimate",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_carbon_impact_estimate_tenant_machine_time",
        "carbon_impact_estimate",
        ["tenant_id", "machine_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.drop_index(op.f("ix_feature_vector_tenant_machine_set_time"), table_name="feature_vector")
    op.drop_index(op.f("ix_telemetry_tenant_machine_time"), table_name="telemetry")
    op.drop_index(op.f("ix_telemetry_tenant_sensor_time"), table_name="telemetry")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_telemetry_tenant_sensor_time"),
        "telemetry",
        ["tenant_id", "sensor_id", sa.literal_column("source_timestamp DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_telemetry_tenant_machine_time"),
        "telemetry",
        ["tenant_id", "machine_id", sa.literal_column("source_timestamp DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_feature_vector_tenant_machine_set_time"),
        "feature_vector",
        ["tenant_id", "machine_id", "feature_set", sa.literal_column("as_of_timestamp DESC")],
        unique=False,
    )
    op.drop_index(
        "ix_carbon_impact_estimate_tenant_machine_time", table_name="carbon_impact_estimate"
    )
    op.drop_index(
        op.f("ix_carbon_impact_estimate_tenant_id"), table_name="carbon_impact_estimate"
    )
    op.drop_index(op.f("ix_carbon_impact_estimate_site_id"), table_name="carbon_impact_estimate")
    op.drop_index(
        op.f("ix_carbon_impact_estimate_machine_id"), table_name="carbon_impact_estimate"
    )
    op.drop_index(
        op.f("ix_carbon_impact_estimate_energy_outcome_verification_id"),
        table_name="carbon_impact_estimate",
    )
    op.drop_index(
        op.f("ix_carbon_impact_estimate_emission_factor_id"),
        table_name="carbon_impact_estimate",
    )
    op.drop_table("carbon_impact_estimate")
    op.drop_index("ix_site_emission_factor_tenant_site", table_name="site_emission_factor")
    op.drop_index(
        op.f("ix_site_emission_factor_tenant_id"), table_name="site_emission_factor"
    )
    op.drop_index(op.f("ix_site_emission_factor_site_id"), table_name="site_emission_factor")
    op.drop_table("site_emission_factor")
    # ### end Alembic commands ###
