"""commissioning_and_device_management

Revision ID: 7b48a4c6273c
Revises: 12a414daf64c
Create Date: 2026-08-19 08:26:53.763527
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '7b48a4c6273c'
down_revision: str | None = '12a414daf64c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commissioning_session',
    sa.Column('machine_id', sa.Uuid(), nullable=False),
    sa.Column('gateway_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIGURING', 'VALIDATING', 'READY', 'COMPLETED', 'FAILED', name='commissioningstatus', native_enum=False, length=32), nullable=False),  # noqa: E501
    sa.Column('capability_level', sa.Enum('NONE', 'BASIC_MONITORING', 'DELIVERY_INTELLIGENCE', 'BEARING_INTELLIGENCE', 'FULL_INTELLIGENCE', name='capabilitylevel', native_enum=False, length=32), nullable=False),  # noqa: E501
    sa.Column('validation_issues', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),  # noqa: E501
    sa.Column('steps_completed', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),  # noqa: E501
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),  # noqa: E501
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),  # noqa: E501
    sa.ForeignKeyConstraint(['tenant_id', 'gateway_id'], ['gateway.tenant_id', 'gateway.id'], name=op.f('fk_commissioning_session_tenant_idgateway_id_gateway')),  # noqa: E501
    sa.ForeignKeyConstraint(['tenant_id', 'machine_id'], ['machine.tenant_id', 'machine.id'], name=op.f('fk_commissioning_session_tenant_idmachine_id_machine')),  # noqa: E501
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_commissioning_session_tenant_id_tenant'), ondelete='RESTRICT'),  # noqa: E501
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commissioning_session')),
    sa.UniqueConstraint('tenant_id', 'id', name=op.f('uq_commissioning_session_tenant_idid'))
    )
    op.create_index(op.f('ix_commissioning_session_machine_id'), 'commissioning_session', ['machine_id'], unique=False)  # noqa: E501
    op.create_index(op.f('ix_commissioning_session_tenant_id'), 'commissioning_session', ['tenant_id'], unique=False)  # noqa: E501
    op.create_table('configuration_snapshot',
    sa.Column('machine_id', sa.Uuid(), nullable=False),
    sa.Column('device_type', sa.Enum('GATEWAY', 'CONTROLLER', 'SENSOR', name='devicetype', native_enum=False, length=32), nullable=False),  # noqa: E501
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),  # noqa: E501
    sa.Column('compatibility_status', sa.Enum('SUPPORTED', 'SUPPORTED_WITH_LIMITATIONS', 'UNKNOWN', 'INCOMPATIBLE', name='compatibilitystatus', native_enum=False, length=32), nullable=False),  # noqa: E501
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),  # noqa: E501
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),  # noqa: E501
    sa.ForeignKeyConstraint(['tenant_id', 'machine_id'], ['machine.tenant_id', 'machine.id'], name=op.f('fk_configuration_snapshot_tenant_idmachine_id_machine')),  # noqa: E501
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_configuration_snapshot_tenant_id_tenant'), ondelete='RESTRICT'),  # noqa: E501
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuration_snapshot')),
    sa.UniqueConstraint('tenant_id', 'id', name=op.f('uq_configuration_snapshot_tenant_idid'))
    )
    op.create_index(op.f('ix_configuration_snapshot_device_id'), 'configuration_snapshot', ['device_id'], unique=False)  # noqa: E501
    op.create_index(op.f('ix_configuration_snapshot_device_type'), 'configuration_snapshot', ['device_type'], unique=False)  # noqa: E501
    op.create_index(op.f('ix_configuration_snapshot_machine_id'), 'configuration_snapshot', ['machine_id'], unique=False)  # noqa: E501
    op.create_index(op.f('ix_configuration_snapshot_tenant_id'), 'configuration_snapshot', ['tenant_id'], unique=False)  # noqa: E501
    op.create_index('uq_configuration_snapshot_current_device', 'configuration_snapshot', ['tenant_id', 'device_type', 'device_id'], unique=True, postgresql_where=sa.text('is_current'))  # noqa: E501
    op.create_table('configuration_change',
    sa.Column('machine_id', sa.Uuid(), nullable=False),
    sa.Column('device_type', sa.Enum('GATEWAY', 'CONTROLLER', 'SENSOR', name='devicetype', native_enum=False, length=32), nullable=False),  # noqa: E501
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('previous_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('new_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('changed_by', sa.String(length=150), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('baseline_review_required', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),  # noqa: E501
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),  # noqa: E501
    sa.ForeignKeyConstraint(['tenant_id', 'machine_id'], ['machine.tenant_id', 'machine.id'], name=op.f('fk_configuration_change_tenant_idmachine_id_machine')),  # noqa: E501
    sa.ForeignKeyConstraint(['tenant_id', 'new_snapshot_id'], ['configuration_snapshot.tenant_id', 'configuration_snapshot.id'], name=op.f('fk_configuration_change_tenant_idnew_snapshot_id_configuration_snapshot')),  # noqa: E501
    sa.ForeignKeyConstraint(['tenant_id', 'previous_snapshot_id'], ['configuration_snapshot.tenant_id', 'configuration_snapshot.id'], name=op.f('fk_configuration_change_tenant_idprevious_snapshot_id_configuration_snapshot')),  # noqa: E501
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_configuration_change_tenant_id_tenant'), ondelete='RESTRICT'),  # noqa: E501
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuration_change')),
    sa.UniqueConstraint('tenant_id', 'id', name=op.f('uq_configuration_change_tenant_idid'))
    )
    op.create_index(op.f('ix_configuration_change_device_id'), 'configuration_change', ['device_id'], unique=False)  # noqa: E501
    op.create_index(op.f('ix_configuration_change_machine_id'), 'configuration_change', ['machine_id'], unique=False)  # noqa: E501
    op.create_index(op.f('ix_configuration_change_tenant_id'), 'configuration_change', ['tenant_id'], unique=False)  # noqa: E501
    # NOTE: autogenerate also proposed dropping ix_feature_vector_tenant_machine_set_time
    # and the two ix_telemetry_tenant_* DESC indexes here — the known DESC-index
    # autogenerate false positive (unrelated to this migration's actual change; see
    # ADR-022). Not applied.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configuration_change_tenant_id'), table_name='configuration_change')
    op.drop_index(op.f('ix_configuration_change_machine_id'), table_name='configuration_change')
    op.drop_index(op.f('ix_configuration_change_device_id'), table_name='configuration_change')
    op.drop_table('configuration_change')
    op.drop_index('uq_configuration_snapshot_current_device', table_name='configuration_snapshot', postgresql_where=sa.text('is_current'))  # noqa: E501
    op.drop_index(op.f('ix_configuration_snapshot_tenant_id'), table_name='configuration_snapshot')
    op.drop_index(op.f('ix_configuration_snapshot_machine_id'), table_name='configuration_snapshot')
    op.drop_index(op.f('ix_configuration_snapshot_device_type'), table_name='configuration_snapshot')  # noqa: E501
    op.drop_index(op.f('ix_configuration_snapshot_device_id'), table_name='configuration_snapshot')
    op.drop_table('configuration_snapshot')
    op.drop_index(op.f('ix_commissioning_session_tenant_id'), table_name='commissioning_session')
    op.drop_index(op.f('ix_commissioning_session_machine_id'), table_name='commissioning_session')
    op.drop_table('commissioning_session')
    # ### end Alembic commands ###
