"""incidents_maintenance_cmms

Revision ID: b2aeeb8329ab
Revises: 13d670ebdb0c
Create Date: 2026-08-18 23:53:41.003588

Autogenerate proposed dropping and recreating `ix_feature_vector_tenant_machine_set_time`/
`ix_telemetry_tenant_machine_time`/`ix_telemetry_tenant_sensor_time` with no actual DDL
difference — the same pre-existing DESC-index comparison false positive documented since
ADR-022 and recurring in every migration this project has generated
(`1f9fe8b7b163`, `db57458c6150`, `4762c2a0e92c`, `13d670ebdb0c`). Removed from both
`upgrade()`/`downgrade()` below.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "b2aeeb8329ab"
down_revision: str | None = "13d670ebdb0c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incident",
        sa.Column("machine_id", sa.Uuid(), nullable=False),
        sa.Column("component_id", sa.Uuid(), nullable=True),
        sa.Column("correlation_key", sa.String(length=150), nullable=False),
        sa.Column(
            "incident_type",
            sa.Enum(
                "NORMAL_OPERATION",
                "LUBRICATION_DELIVERY_DEGRADATION",
                "DEVELOPING_RESTRICTION_PATTERN",
                "DELIVERY_BLOCKAGE_PATTERN",
                "POSSIBLE_LEAKAGE_PATTERN",
                "PUMP_PERFORMANCE_DEGRADATION",
                "LOW_LUBRICANT_AVAILABILITY",
                "BEARING_CONDITION_DEGRADATION",
                "INDEPENDENT_BEARING_CONDITION",
                "SENSOR_OR_DATA_QUALITY_LIMITATION",
                "INSUFFICIENT_EVIDENCE",
                "AMBIGUOUS_CONDITION",
                name="conditiontype",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "INFO",
                "WARNING",
                "HIGH",
                "CRITICAL",
                name="conditionseverity",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "priority",
            sa.Enum(
                "MONITOR",
                "PLANNED",
                "HIGH",
                "URGENT",
                name="decisionpriority",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "state",
            sa.Enum(
                "DETECTED",
                "OPEN",
                "ACKNOWLEDGED",
                "INVESTIGATING",
                "ACTION_PLANNED",
                "RESOLVED",
                "CLOSED",
                "REOPENED",
                name="incidentstate",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column("first_detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "condition_assessment_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "decision_assessment_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "prognostic_assessment_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "rule_finding_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "ml_result_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "state_estimate_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "evidence_refs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),  # noqa: E501
        sa.Column("assigned_to", sa.String(length=150), nullable=True),
        sa.Column("policy_version", sa.String(length=20), nullable=False),
        sa.Column("engine_version", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tenant_id", "machine_id"],
            ["machine.tenant_id", "machine.id"],
            name=op.f("fk_incident_tenant_idmachine_id_machine"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_incident_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incident")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_incident_tenant_idid")),
    )
    op.create_index(op.f("ix_incident_component_id"), "incident", ["component_id"], unique=False)
    op.create_index(
        op.f("ix_incident_correlation_key"), "incident", ["correlation_key"], unique=False
    )  # noqa: E501
    op.create_index(op.f("ix_incident_incident_type"), "incident", ["incident_type"], unique=False)
    op.create_index(op.f("ix_incident_machine_id"), "incident", ["machine_id"], unique=False)
    op.create_index(op.f("ix_incident_state"), "incident", ["state"], unique=False)
    op.create_index(op.f("ix_incident_tenant_id"), "incident", ["tenant_id"], unique=False)
    op.create_index(
        "ix_incident_tenant_machine_time",
        "incident",
        ["tenant_id", "machine_id", sa.literal_column("created_at DESC")],
        unique=False,
    )  # noqa: E501
    op.create_index(
        "uq_incident_active_correlation_key",
        "incident",
        ["tenant_id", "machine_id", "correlation_key"],
        unique=True,
        postgresql_where=sa.text("state NOT IN ('RESOLVED', 'CLOSED')"),
    )  # noqa: E501
    op.create_table(
        "incident_event",
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "INCIDENT_CREATED",
                "EVIDENCE_ADDED",
                "SEVERITY_CHANGED",
                "PRIORITY_CHANGED",
                "ACKNOWLEDGED",
                "INVESTIGATION_STARTED",
                "ACTION_PLANNED",
                "TECHNICIAN_FINDING_RECORDED",
                "RESOLVED",
                "CLOSED",
                "REOPENED",
                name="incidenteventtype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),  # noqa: E501
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tenant_id", "incident_id"],
            ["incident.tenant_id", "incident.id"],
            name=op.f("fk_incident_event_tenant_idincident_id_incident"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_incident_event_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incident_event")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_incident_event_tenant_idid")),
    )
    op.create_index(
        op.f("ix_incident_event_incident_id"), "incident_event", ["incident_id"], unique=False
    )  # noqa: E501
    op.create_index(
        op.f("ix_incident_event_tenant_id"), "incident_event", ["tenant_id"], unique=False
    )  # noqa: E501
    op.create_index(
        "ix_incident_event_tenant_incident_time",
        "incident_event",
        ["tenant_id", "incident_id", "created_at"],
        unique=False,
    )  # noqa: E501
    op.create_table(
        "maintenance_case",
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("machine_id", sa.Uuid(), nullable=False),
        sa.Column("component_id", sa.Uuid(), nullable=True),
        sa.Column("condition_assessment_id", sa.Uuid(), nullable=False),
        sa.Column("decision_assessment_id", sa.Uuid(), nullable=False),
        sa.Column(
            "recommended_action",
            sa.Enum(
                "CONTINUE_MONITORING",
                "VERIFY_SENSOR",
                "INSPECT_LUBRICATION_PATH",
                "INSPECT_DISTRIBUTOR",
                "CHECK_RESERVOIR",
                "CHECK_PUMP",
                "INSPECT_BEARING",
                "SCHEDULE_MAINTENANCE",
                "REQUEST_ADDITIONAL_MEASUREMENT",
                name="recommendedaction",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "recommended_window",
            sa.Enum(
                "NOW",
                "WITHIN_HOURS",
                "NEXT_PLANNED_MAINTENANCE",
                "MONITOR",
                name="recommendedwindow",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "priority",
            sa.Enum(
                "MONITOR",
                "PLANNED",
                "HIGH",
                "URGENT",
                name="decisionpriority",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column("human_review_required", sa.Boolean(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "REVIEW_REQUIRED",
                "NOT_STARTED",
                "PLANNED",
                "IN_PROGRESS",
                "AWAITING_VERIFICATION",
                "COMPLETED",
                "CANCELLED",
                name="maintenancestate",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "checklist",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),  # noqa: E501
        sa.Column("checklist_template_id", sa.String(length=60), nullable=False),
        sa.Column(
            "feedback_classification",
            sa.Enum(
                "TRUE_POSITIVE",
                "FALSE_POSITIVE",
                "MISSED_FAILURE",
                "INCONCLUSIVE",
                name="feedbackclassification",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),  # noqa: E501
        sa.Column("planned_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("policy_version", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tenant_id", "incident_id"],
            ["incident.tenant_id", "incident.id"],
            name=op.f("fk_maintenance_case_tenant_idincident_id_incident"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_maintenance_case_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maintenance_case")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_maintenance_case_tenant_idid")),
    )
    op.create_index(
        op.f("ix_maintenance_case_component_id"), "maintenance_case", ["component_id"], unique=False
    )  # noqa: E501
    op.create_index(
        op.f("ix_maintenance_case_incident_id"), "maintenance_case", ["incident_id"], unique=False
    )  # noqa: E501
    op.create_index(
        op.f("ix_maintenance_case_machine_id"), "maintenance_case", ["machine_id"], unique=False
    )  # noqa: E501
    op.create_index(op.f("ix_maintenance_case_state"), "maintenance_case", ["state"], unique=False)
    op.create_index(
        op.f("ix_maintenance_case_tenant_id"), "maintenance_case", ["tenant_id"], unique=False
    )  # noqa: E501
    op.create_index(
        "uq_maintenance_case_active_incident",
        "maintenance_case",
        ["tenant_id", "incident_id"],
        unique=True,
        postgresql_where=sa.text("state NOT IN ('COMPLETED', 'CANCELLED')"),
    )  # noqa: E501
    op.create_table(
        "demo_cmms_work_order",
        sa.Column("maintenance_case_id", sa.Uuid(), nullable=False),
        sa.Column("external_reference", sa.String(length=60), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("asset_reference", sa.String(length=100), nullable=False),
        sa.Column(
            "priority",
            sa.Enum(
                "MONITOR",
                "PLANNED",
                "HIGH",
                "URGENT",
                name="decisionpriority",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "SUBMITTED",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                name="cmmsworkorderstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "recommended_window",
            sa.Enum(
                "NOW",
                "WITHIN_HOURS",
                "NEXT_PLANNED_MAINTENANCE",
                "MONITOR",
                name="recommendedwindow",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "checklist",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),  # noqa: E501
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tenant_id", "maintenance_case_id"],
            ["maintenance_case.tenant_id", "maintenance_case.id"],
            name=op.f("fk_demo_cmms_work_order_tenant_idmaintenance_case_id_maintenance_case"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_demo_cmms_work_order_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_demo_cmms_work_order")),
        sa.UniqueConstraint(
            "external_reference", name=op.f("uq_demo_cmms_work_order_external_reference")
        ),  # noqa: E501
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_demo_cmms_work_order_tenant_idid")),
        sa.UniqueConstraint(
            "tenant_id", "maintenance_case_id", name="uq_demo_cmms_work_order_case"
        ),
    )
    op.create_index(
        op.f("ix_demo_cmms_work_order_maintenance_case_id"),
        "demo_cmms_work_order",
        ["maintenance_case_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        op.f("ix_demo_cmms_work_order_tenant_id"),
        "demo_cmms_work_order",
        ["tenant_id"],
        unique=False,
    )  # noqa: E501
    op.create_table(
        "feedback_record",
        sa.Column("maintenance_case_id", sa.Uuid(), nullable=False),
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("condition_assessment_id", sa.Uuid(), nullable=False),
        sa.Column("decision_assessment_id", sa.Uuid(), nullable=False),
        sa.Column(
            "classification",
            sa.Enum(
                "TRUE_POSITIVE",
                "FALSE_POSITIVE",
                "MISSED_FAILURE",
                "INCONCLUSIVE",
                name="feedbackclassification",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column("confirmed_component", sa.String(length=150), nullable=True),
        sa.Column("confirmed_finding", sa.Text(), nullable=True),
        sa.Column("post_action_condition_type", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("recorded_by", sa.String(length=150), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tenant_id", "maintenance_case_id"],
            ["maintenance_case.tenant_id", "maintenance_case.id"],
            name=op.f("fk_feedback_record_tenant_idmaintenance_case_id_maintenance_case"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_feedback_record_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback_record")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_feedback_record_tenant_idid")),
    )
    op.create_index(
        op.f("ix_feedback_record_classification"),
        "feedback_record",
        ["classification"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        op.f("ix_feedback_record_incident_id"), "feedback_record", ["incident_id"], unique=False
    )  # noqa: E501
    op.create_index(
        op.f("ix_feedback_record_maintenance_case_id"),
        "feedback_record",
        ["maintenance_case_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        op.f("ix_feedback_record_tenant_id"), "feedback_record", ["tenant_id"], unique=False
    )  # noqa: E501
    op.create_table(
        "maintenance_action",
        sa.Column("maintenance_case_id", sa.Uuid(), nullable=False),
        sa.Column(
            "action_type",
            sa.Enum(
                "INSPECTED",
                "CLEANED",
                "REFILLED",
                "COMPONENT_REPLACED",
                "ADJUSTMENT_RECOMMENDED",
                "NO_ACTION_REQUIRED",
                "ESCALATED",
                name="maintenanceactiontype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("recorded_by", sa.String(length=150), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tenant_id", "maintenance_case_id"],
            ["maintenance_case.tenant_id", "maintenance_case.id"],
            name=op.f("fk_maintenance_action_tenant_idmaintenance_case_id_maintenance_case"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_maintenance_action_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maintenance_action")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_maintenance_action_tenant_idid")),
    )
    op.create_index(
        op.f("ix_maintenance_action_maintenance_case_id"),
        "maintenance_action",
        ["maintenance_case_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        "ix_maintenance_action_tenant_case_time",
        "maintenance_action",
        ["tenant_id", "maintenance_case_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        op.f("ix_maintenance_action_tenant_id"), "maintenance_action", ["tenant_id"], unique=False
    )  # noqa: E501
    op.create_table(
        "technician_finding",
        sa.Column("maintenance_case_id", sa.Uuid(), nullable=False),
        sa.Column(
            "result",
            sa.Enum(
                "CONFIRMED",
                "NOT_CONFIRMED",
                "PARTIALLY_CONFIRMED",
                "DIFFERENT_ISSUE_FOUND",
                "UNABLE_TO_VERIFY",
                name="technicianfindingresult",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column("component", sa.String(length=150), nullable=True),
        sa.Column("observed_issue", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("technician_identifier", sa.String(length=150), nullable=False),
        sa.Column(
            "attachments_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),  # noqa: E501
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tenant_id", "maintenance_case_id"],
            ["maintenance_case.tenant_id", "maintenance_case.id"],
            name=op.f("fk_technician_finding_tenant_idmaintenance_case_id_maintenance_case"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_technician_finding_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_technician_finding")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_technician_finding_tenant_idid")),
    )
    op.create_index(
        op.f("ix_technician_finding_maintenance_case_id"),
        "technician_finding",
        ["maintenance_case_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        "ix_technician_finding_tenant_case_time",
        "technician_finding",
        ["tenant_id", "maintenance_case_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        op.f("ix_technician_finding_tenant_id"), "technician_finding", ["tenant_id"], unique=False
    )  # noqa: E501
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_technician_finding_tenant_id"), table_name="technician_finding")
    op.drop_index("ix_technician_finding_tenant_case_time", table_name="technician_finding")
    op.drop_index(
        op.f("ix_technician_finding_maintenance_case_id"), table_name="technician_finding"
    )  # noqa: E501
    op.drop_table("technician_finding")
    op.drop_index(op.f("ix_maintenance_action_tenant_id"), table_name="maintenance_action")
    op.drop_index("ix_maintenance_action_tenant_case_time", table_name="maintenance_action")
    op.drop_index(
        op.f("ix_maintenance_action_maintenance_case_id"), table_name="maintenance_action"
    )  # noqa: E501
    op.drop_table("maintenance_action")
    op.drop_index(op.f("ix_feedback_record_tenant_id"), table_name="feedback_record")
    op.drop_index(op.f("ix_feedback_record_maintenance_case_id"), table_name="feedback_record")
    op.drop_index(op.f("ix_feedback_record_incident_id"), table_name="feedback_record")
    op.drop_index(op.f("ix_feedback_record_classification"), table_name="feedback_record")
    op.drop_table("feedback_record")
    op.drop_index(op.f("ix_demo_cmms_work_order_tenant_id"), table_name="demo_cmms_work_order")
    op.drop_index(
        op.f("ix_demo_cmms_work_order_maintenance_case_id"), table_name="demo_cmms_work_order"
    )  # noqa: E501
    op.drop_table("demo_cmms_work_order")
    op.drop_index(
        "uq_maintenance_case_active_incident",
        table_name="maintenance_case",
        postgresql_where=sa.text("state NOT IN ('COMPLETED', 'CANCELLED')"),
    )  # noqa: E501
    op.drop_index(op.f("ix_maintenance_case_tenant_id"), table_name="maintenance_case")
    op.drop_index(op.f("ix_maintenance_case_state"), table_name="maintenance_case")
    op.drop_index(op.f("ix_maintenance_case_machine_id"), table_name="maintenance_case")
    op.drop_index(op.f("ix_maintenance_case_incident_id"), table_name="maintenance_case")
    op.drop_index(op.f("ix_maintenance_case_component_id"), table_name="maintenance_case")
    op.drop_table("maintenance_case")
    op.drop_index("ix_incident_event_tenant_incident_time", table_name="incident_event")
    op.drop_index(op.f("ix_incident_event_tenant_id"), table_name="incident_event")
    op.drop_index(op.f("ix_incident_event_incident_id"), table_name="incident_event")
    op.drop_table("incident_event")
    op.drop_index(
        "uq_incident_active_correlation_key",
        table_name="incident",
        postgresql_where=sa.text("state NOT IN ('RESOLVED', 'CLOSED')"),
    )  # noqa: E501
    op.drop_index("ix_incident_tenant_machine_time", table_name="incident")
    op.drop_index(op.f("ix_incident_tenant_id"), table_name="incident")
    op.drop_index(op.f("ix_incident_state"), table_name="incident")
    op.drop_index(op.f("ix_incident_machine_id"), table_name="incident")
    op.drop_index(op.f("ix_incident_incident_type"), table_name="incident")
    op.drop_index(op.f("ix_incident_correlation_key"), table_name="incident")
    op.drop_index(op.f("ix_incident_component_id"), table_name="incident")
    op.drop_table("incident")
    # ### end Alembic commands ###
