"""energy_assessment

Revision ID: c67d71dabca3
Revises: 7b48a4c6273c
Create Date: 2026-08-24 14:37:41.557856

Autogenerate also proposed dropping/re-adding `ix_feature_vector_tenant_machine_set_time`,
`ix_telemetry_tenant_machine_time`, and `ix_telemetry_tenant_sensor_time` — the same known
`DESC`-index false positive documented in migration `1f9fe8b7b163`/`db57458c6150`/
`4762c2a0e92c` (autogenerate's index-signature comparison doesn't recognize
`sa.text(...) DESC`-built indexes as unchanged). Those three indexes are intentionally
left untouched by this migration.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c67d71dabca3"
down_revision: str | None = "7b48a4c6273c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "energy_assessment",
        sa.Column("machine_id", sa.Uuid(), nullable=False),
        sa.Column("power_sensor_id", sa.Uuid(), nullable=False),
        sa.Column("as_of_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actual_power_kw", sa.Float(), nullable=True),
        sa.Column("expected_power_kw", sa.Float(), nullable=True),
        sa.Column("expected_lower_kw", sa.Float(), nullable=True),
        sa.Column("expected_upper_kw", sa.Float(), nullable=True),
        sa.Column("residual_kw", sa.Float(), nullable=True),
        sa.Column("residual_pct", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "WITHIN_EXPECTED_RANGE",
                "ELEVATED_ENERGY_DEMAND",
                "BELOW_EXPECTED_RANGE",
                "INSUFFICIENT_BASELINE",
                "INSUFFICIENT_DATA",
                "DATA_QUALITY_LIMITED",
                name="energyassessmentstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "data_quality_state",
            sa.Enum(
                "TRUSTED",
                "USABLE_WITH_CAUTION",
                "UNUSABLE",
                name="qualitystate",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "baseline_source",
            sa.Enum(
                "EXACT_CONTEXT",
                "OPERATING_STATE",
                "SENSOR_LEVEL",
                "ENGINEERING_REFERENCE",
                "NONE",
                name="baselinesourcekind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("baseline_profile_id", sa.Uuid(), nullable=True),
        sa.Column("operating_state", sa.String(length=40), nullable=True),
        sa.Column("engine_version", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "machine_id"],
            ["machine.tenant_id", "machine.id"],
            name=op.f("fk_energy_assessment_tenant_idmachine_id_machine"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "power_sensor_id"],
            ["sensor.tenant_id", "sensor.id"],
            name=op.f("fk_energy_assessment_tenant_idpower_sensor_id_sensor"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_energy_assessment_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_energy_assessment")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_energy_assessment_tenant_idid")),
    )
    op.create_index(
        op.f("ix_energy_assessment_as_of_timestamp"),
        "energy_assessment",
        ["as_of_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_energy_assessment_machine_id"), "energy_assessment", ["machine_id"], unique=False
    )
    op.create_index(
        op.f("ix_energy_assessment_power_sensor_id"),
        "energy_assessment",
        ["power_sensor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_energy_assessment_tenant_id"), "energy_assessment", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_energy_assessment_tenant_machine_time",
        "energy_assessment",
        ["tenant_id", "machine_id", sa.literal_column("as_of_timestamp DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_energy_assessment_tenant_machine_time", table_name="energy_assessment")
    op.drop_index(op.f("ix_energy_assessment_tenant_id"), table_name="energy_assessment")
    op.drop_index(op.f("ix_energy_assessment_power_sensor_id"), table_name="energy_assessment")
    op.drop_index(op.f("ix_energy_assessment_machine_id"), table_name="energy_assessment")
    op.drop_index(op.f("ix_energy_assessment_as_of_timestamp"), table_name="energy_assessment")
    op.drop_table("energy_assessment")
    # ### end Alembic commands ###
