"""lubrication_energy_attribution

Revision ID: ed804824fd91
Revises: c67d71dabca3
Create Date: 2026-08-24 16:50:45.877760

Autogenerate also proposed dropping/re-adding `ix_feature_vector_tenant_machine_set_time`,
`ix_telemetry_tenant_machine_time`, and `ix_telemetry_tenant_sensor_time` — the same known
`DESC`-index false positive documented in migration `1f9fe8b7b163`/`db57458c6150`/
`4762c2a0e92c`/`c67d71dabca3` (autogenerate's index-signature comparison doesn't recognize
`sa.text(...) DESC`-built indexes as unchanged). Those three indexes are intentionally
left untouched by this migration.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "ed804824fd91"
down_revision: str | None = "c67d71dabca3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lubrication_energy_attribution",
        sa.Column("machine_id", sa.Uuid(), nullable=False),
        sa.Column("energy_assessment_id", sa.Uuid(), nullable=False),
        sa.Column("as_of_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "attribution_level",
            sa.Enum(
                "NO_EVIDENCE",
                "POSSIBLE",
                "MODERATE",
                "STRONG",
                name="attributionlevel",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("energy_residual_kw", sa.Float(), nullable=True),
        sa.Column("energy_residual_pct", sa.Float(), nullable=True),
        sa.Column(
            "supporting_evidence",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "contradicting_evidence",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "limiting_factors",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "alternative_explanations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("data_quality_state", sa.String(length=20), nullable=False),
        sa.Column("condition_assessment_id", sa.Uuid(), nullable=True),
        sa.Column("policy_version", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "energy_assessment_id"],
            ["energy_assessment.tenant_id", "energy_assessment.id"],
            name=op.f(
                "fk_lubrication_energy_attribution_tenant_idenergy_assessment_id_energy_assessment"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "machine_id"],
            ["machine.tenant_id", "machine.id"],
            name=op.f("fk_lubrication_energy_attribution_tenant_idmachine_id_machine"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_lubrication_energy_attribution_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lubrication_energy_attribution")),
        sa.UniqueConstraint(
            "tenant_id", "id", name=op.f("uq_lubrication_energy_attribution_tenant_idid")
        ),
    )
    op.create_index(
        op.f("ix_lubrication_energy_attribution_as_of_timestamp"),
        "lubrication_energy_attribution",
        ["as_of_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lubrication_energy_attribution_energy_assessment_id"),
        "lubrication_energy_attribution",
        ["energy_assessment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lubrication_energy_attribution_machine_id"),
        "lubrication_energy_attribution",
        ["machine_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lubrication_energy_attribution_tenant_id"),
        "lubrication_energy_attribution",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_lubrication_energy_attribution_tenant_machine_time",
        "lubrication_energy_attribution",
        ["tenant_id", "machine_id", sa.literal_column("as_of_timestamp DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_lubrication_energy_attribution_tenant_machine_time",
        table_name="lubrication_energy_attribution",
    )
    op.drop_index(
        op.f("ix_lubrication_energy_attribution_tenant_id"),
        table_name="lubrication_energy_attribution",
    )
    op.drop_index(
        op.f("ix_lubrication_energy_attribution_machine_id"),
        table_name="lubrication_energy_attribution",
    )
    op.drop_index(
        op.f("ix_lubrication_energy_attribution_energy_assessment_id"),
        table_name="lubrication_energy_attribution",
    )
    op.drop_index(
        op.f("ix_lubrication_energy_attribution_as_of_timestamp"),
        table_name="lubrication_energy_attribution",
    )
    op.drop_table("lubrication_energy_attribution")
    # ### end Alembic commands ###
